impl WasmCodeGen {
    pub fn emit_wat(program: &Program) -> Result<String> {
        WASM_STRINGS.with(|s| s.borrow_mut().clear());
        let aliases = program.collect_type_aliases();
        
        WASM_STRUCTS.with(|s| {
            let mut structs = s.borrow_mut();
            structs.clear();
            for (name, ty) in &aliases {
                if let Type::Custom(def) = ty {
                    if let Some(fields_str) = def.strip_prefix("struct:") {
                        let inner = if let Some(idx) = fields_str.find('{') {
                            fields_str[idx+1..fields_str.len()-1].to_string()
                        } else {
                            fields_str.to_string()
                        };
                        let mut field_names = Vec::new();
                        if !inner.is_empty() {
                            for f in inner.split(',') {
                                let parts: Vec<&str> = f.split(':').collect();
                                field_names.push(parts[0].to_string());
                            }
                        }
                        structs.insert(name.clone(), field_names);
                    }
                } else if let Type::Struct { fields, .. } = ty {
                    structs.insert(name.clone(), fields.iter().map(|(n, _)| n.clone()).collect());
                }
            }
        });
        
        let needs_list_rt = Self::program_needs_list_runtime(program);
        // Emit function bodies first so we can gate host imports + heap on real use (E-M D↓/W↓):
        // pure Int programs must not pull streq/str_contains/println_str or $heap.
        let mut funcs_wat = String::new();
        for item in &program.items {
            if let Item::Function(func) = item {
                let f_wat = Self::emit_function(func, &aliases)?;
                funcs_wat.push_str(&f_wat);
                funcs_wat.push('\n');
            }
        }
        // Import surface from actual call sites in emitted WAT (not speculative AST).
        // Match `call $println` without also matching `call $println_str`.
        let needs_println = funcs_wat.lines().any(|l| {
            let t = l.trim();
            t == "call $println" || t.starts_with("call $println ")
        });
        let needs_println_str = funcs_wat.contains("call $println_str");
        // `$list_str_eq` RT calls `$streq` — import when either body or eq RT needs it.
        let needs_list_str_eq = funcs_wat.contains("call $list_str_eq");
        let needs_streq = funcs_wat.contains("call $streq") || needs_list_str_eq;
        let needs_str_contains = funcs_wat.contains("call $str_contains");
        // Heap only when bodies actually bump-allocate (list RT / str_slice / str_concat).
        let body_uses_heap = funcs_wat.contains("global.get $heap");

        let mut wat = String::new();
        wat.push_str(";; ===================================================================\n");
        wat.push_str(";; openOODA WebAssembly Text Format (.wat) Target Backend\n");
        wat.push_str(";; Generated by `ooda build --target wasm` (v0.24.0-alpha)\n");
        wat.push_str(";; ===================================================================\n\n");
        wat.push_str("(module\n");
        if needs_println {
            wat.push_str("  (import \"env\" \"println\" (func $println (param i64)))\n");
        }
        if needs_println_str {
            wat.push_str("  (import \"env\" \"println_str\" (func $println_str (param i32)))\n");
        }
        if needs_streq {
            wat.push_str("  (import \"env\" \"streq\" (func $streq (param i32 i32) (result i32)))\n");
        }
        if needs_str_contains {
            wat.push_str(
                "  (import \"env\" \"str_contains\" (func $str_contains (param i32 i32) (result i32)))\n",
            );
        }
        if needs_println || needs_println_str || needs_streq || needs_str_contains {
            wat.push('\n');
        }

        let string_count = WASM_STRINGS.with(|s| s.borrow().len());
        let needs_heap = needs_list_rt || body_uses_heap;
        let needs_memory = needs_list_rt
            || string_count > 0
            || needs_heap
            || funcs_wat.contains("i32.load8_u");
        if needs_memory {
            wat.push_str("  (memory 1)\n");
            wat.push_str("  (export \"memory\" (memory 0))\n");
            let mut offset = 0usize;
            WASM_STRINGS.with(|strings| {
                for s in strings.borrow().iter() {
                    let mut hex_str = String::new();
                    for b in s.as_bytes() {
                        hex_str.push_str(&format!("\\{:02x}", b));
                    }
                    hex_str.push_str("\\00");
                    wat.push_str(&format!("  (data (i32.const {}) \"{}\")\n", offset, hex_str));
                    offset += s.len() + 1;
                }
            });
            if needs_heap {
                let heap_start = (offset + 15) & !15;
                wat.push_str(&format!(
                    "  (global $heap (mut i32) (i32.const {}))\n",
                    heap_start
                ));
            }
            if needs_list_rt {
                // Base list RT always when lists used; eq helpers only if called (W↓).
                wat.push_str(Self::list_runtime_wat());
                if funcs_wat.contains("call $list_eq") {
                    wat.push_str(Self::list_eq_runtime_wat());
                }
                if needs_list_str_eq {
                    wat.push_str(Self::list_str_eq_runtime_wat());
                }
            }
        }

        wat.push_str(&funcs_wat);
        wat.push_str(")\n");
        Self::validate_wat(&wat)?;
        Ok(wat)
    }


    /// List[Int] bump-heap runtime (only emitted when the program uses lists).
    /// Deep equality (`$list_eq`) is separate — see `list_eq_runtime_wat`.
    fn list_runtime_wat() -> &'static str {
        r#"
  (func $list_new (result i32)
    (local $ptr i32)
    (local.set $ptr (global.get $heap))
    (global.set $heap (i32.add (local.get $ptr) (i32.const 16)))
    (i32.store (local.get $ptr) (i32.const 0))
    (i32.store offset=4 (local.get $ptr) (i32.const 0))
    (i32.store offset=8 (local.get $ptr) (i32.const 0))
    (local.get $ptr)
    return
  )
  (func $list_len (param $list i32) (result i64)
    (i64.extend_i32_u (i32.load (local.get $list)))
    return
  )
  (func $list_get (param $list i32) (param $index i64) (result i64)
    (local $data i32)
    (local.set $data (i32.load offset=8 (local.get $list)))
    (i64.load (i32.add (local.get $data) (i32.mul (i32.wrap_i64 (local.get $index)) (i32.const 8))))
    return
  )
  (func $list_push (param $list i32) (param $elem i64) (result i32)
    (local $len i32) (local $cap i32) (local $data i32) (local $new_cap i32) (local $new_data i32) (local $i i32)
    (local.set $len (i32.load (local.get $list)))
    (local.set $cap (i32.load offset=4 (local.get $list)))
    (local.set $data (i32.load offset=8 (local.get $list)))
    (if (i32.eq (local.get $len) (local.get $cap))
      (then
        (if (i32.eqz (local.get $cap))
          (then (local.set $new_cap (i32.const 4)))
          (else (local.set $new_cap (i32.mul (local.get $cap) (i32.const 2))))
        )
        (local.set $new_data (global.get $heap))
        (global.set $heap (i32.add (local.get $new_data) (i32.mul (local.get $new_cap) (i32.const 8))))
        (if (i32.gt_u (local.get $cap) (i32.const 0))
          (then
            (local.set $i (i32.const 0))
            (loop $copy_loop
              (i64.store
                (i32.add (local.get $new_data) (i32.mul (local.get $i) (i32.const 8)))
                (i64.load (i32.add (local.get $data) (i32.mul (local.get $i) (i32.const 8))))
              )
              (local.set $i (i32.add (local.get $i) (i32.const 1)))
              (br_if $copy_loop (i32.lt_u (local.get $i) (local.get $cap)))
            )
          )
        )
        (i32.store offset=4 (local.get $list) (local.get $new_cap))
        (i32.store offset=8 (local.get $list) (local.get $new_data))
        (local.set $data (local.get $new_data))
      )
    )
    (i64.store (i32.add (local.get $data) (i32.mul (local.get $len) (i32.const 8))) (local.get $elem))
    (i32.store (local.get $list) (i32.add (local.get $len) (i32.const 1)))
    (local.get $list)
    return
  )
"#
    }


    /// Deep List[Int] equality — only when `call $list_eq` appears (W↓).
    fn list_eq_runtime_wat() -> &'static str {
        r#"
  (func $list_eq (param $a i32) (param $b i32) (result i32)
    (local $len_a i32) (local $len_b i32) (local $data_a i32) (local $data_b i32) (local $i i32)
    (if (i32.eq (local.get $a) (local.get $b)) (then (return (i32.const 1))))
    (local.set $len_a (i32.load (local.get $a)))
    (local.set $len_b (i32.load (local.get $b)))
    (if (i32.ne (local.get $len_a) (local.get $len_b)) (then (return (i32.const 0))))
    (local.set $data_a (i32.load offset=8 (local.get $a)))
    (local.set $data_b (i32.load offset=8 (local.get $b)))
    (local.set $i (i32.const 0))
    (loop $cmp_loop
      (if (i32.eq (local.get $i) (local.get $len_a)) (then (return (i32.const 1))))
      (if (i64.ne
            (i64.load (i32.add (local.get $data_a) (i32.mul (local.get $i) (i32.const 8))))
            (i64.load (i32.add (local.get $data_b) (i32.mul (local.get $i) (i32.const 8))))
          )
          (then (return (i32.const 0)))
      )
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $cmp_loop)
    )
    (i32.const 0)
    return
  )
"#
    }


    /// List[String] content equality via host `$streq` per element (not i64 pointer eq).
    /// Only injected when `call $list_str_eq` appears (W↓). Aligns with interpreter String PartialEq.
    fn list_str_eq_runtime_wat() -> &'static str {
        r#"
  (func $list_str_eq (param $a i32) (param $b i32) (result i32)
    (local $len_a i32) (local $len_b i32) (local $data_a i32) (local $data_b i32) (local $i i32) (local $pa i32) (local $pb i32)
    (if (i32.eq (local.get $a) (local.get $b)) (then (return (i32.const 1))))
    (local.set $len_a (i32.load (local.get $a)))
    (local.set $len_b (i32.load (local.get $b)))
    (if (i32.ne (local.get $len_a) (local.get $len_b)) (then (return (i32.const 0))))
    (local.set $data_a (i32.load offset=8 (local.get $a)))
    (local.set $data_b (i32.load offset=8 (local.get $b)))
    (local.set $i (i32.const 0))
    (loop $cmp_loop
      (if (i32.eq (local.get $i) (local.get $len_a)) (then (return (i32.const 1))))
      (local.set $pa (i32.wrap_i64 (i64.load (i32.add (local.get $data_a) (i32.mul (local.get $i) (i32.const 8))))))
      (local.set $pb (i32.wrap_i64 (i64.load (i32.add (local.get $data_b) (i32.mul (local.get $i) (i32.const 8))))))
      (if (i32.eqz (call $streq (local.get $pa) (local.get $pb))) (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $cmp_loop)
    )
    (i32.const 0)
    return
  )
"#
    }

}
