impl Gen {
    fn new() -> Self {
        Self {
            structs: HashMap::new(),
            type_aliases: HashMap::new(),
            fn_ret: HashMap::new(),
            functions: Vec::new(),
            prelude: String::new(),
            body: String::new(),
            tmp: 0,
            c_main: false,
            fn_void: false,
            with_host_ffi: false,
        }
    }


    fn fresh(&mut self, p: &str) -> String {
        self.tmp += 1;
        format!("{}_{}", p, self.tmp)
    }


    /// Build C lvalue for `object.field` where object is Variable or nested `.f` Calls.
    fn c_field_lvalue(object: &Expression, field: &str) -> Result<String> {
        let mut segs: Vec<String> = Vec::new();
        let mut cur = object;
        loop {
            match cur {
                Expression::Variable(name, _) => {
                    segs.insert(0, name.clone());
                    break;
                }
                Expression::Call { name, args, .. }
                    if name.starts_with('.') && args.len() == 1 =>
                {
                    segs.insert(0, name[1..].to_string());
                    cur = &args[0];
                }
                _ => bail!("C backend: field assign requires variable or field-path receiver"),
            }
        }
        segs.push(field.to_string());
        Ok(segs.join("."))
    }


    fn finish(self) -> String {
        let mut s = String::new();
        s.push_str("/* generated by openOODA CHS C backend — do not edit */\n");
        s.push_str("#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <stdbool.h>\n#include <unistd.h>\n");
        s.push_str("/* runtime decls (defined in chs_rt.c) */\n");
        s.push_str("typedef struct { char *data; long long len; } OoStr;\n");
        s.push_str("typedef struct { long long *data; long long len; long long cap; } OoIList;\n");
        s.push_str("typedef struct { OoStr *data; long long len; long long cap; } OoSList;\n");
        s.push_str("typedef struct { int ok; OoStr val; } OoResS;\n");
        s.push_str("typedef struct { int ok; OoStr err; } OoResV;\n");
        s.push_str("OoStr oo_str_lit(const char*); OoStr oo_str_concat(OoStr,OoStr);\n");
        s.push_str("long long oo_str_byte_len(OoStr); long long oo_chars_len(OoStr);\n");
        s.push_str("OoStr oo_char_at(OoStr,long long); OoStr oo_str_slice(OoStr,long long,long long);\n");
        s.push_str("int oo_str_contains(OoStr,OoStr);\n");
        s.push_str("int oo_char_is_digit(OoStr); int oo_char_is_alpha(OoStr); int oo_char_is_space(OoStr);\n");
        s.push_str("OoIList oo_ilist_new(void); OoIList oo_ilist_push(OoIList,long long);\n");
        s.push_str("long long oo_ilist_get(OoIList,long long); long long oo_ilist_len(OoIList);\n");
        s.push_str("OoSList oo_slist_new(void); OoSList oo_slist_push(OoSList,OoStr);\n");
        s.push_str("OoStr oo_slist_get(OoSList,long long); long long oo_slist_len(OoSList);\n");
        s.push_str("OoResS oo_read_file(OoStr); OoResV oo_write_file(OoStr,OoStr); int oo_path_exists(OoStr); long long oo_file_size(OoStr); OoResS oo_env_get(OoStr);\n");
        s.push_str("void oo_print_str(OoStr); void oo_print_int(long long); void oo_print_bool(int); void oo_println(void);\n");
        s.push_str("int oo_str_eq(OoStr,OoStr); int oo_str_contains(OoStr,OoStr);\n");
        s.push_str("OoStr oo_int_to_str(long long); OoStr oo_str_trim(OoStr); OoStr oo_str_to_lowercase(OoStr);\n");
        // Host FFI only when the program calls it — pure CHS never needs libooda.a.
        if self.with_host_ffi {
            s.push_str("/* Host FFI (libooda.a) — stage-0 dumps + chs_build */\n");
            s.push_str("char *ooda_host_ast_dump(const char *path);\n");
            s.push_str("char *ooda_host_check(const char *path);\n");
            s.push_str("char *ooda_host_token_dump(const char *path);\n");
            s.push_str("int ooda_host_chs_build(const char *src, const char *out_bin);\n");
            s.push_str("void ooda_host_free(char *p);\n");
            s.push_str("OoStr oo_host_ast_dump(OoStr path);\n");
            s.push_str("OoStr oo_host_check(OoStr path);\n");
            s.push_str("OoStr oo_host_token_dump(OoStr path);\n");
            s.push_str("OoResS oo_chs_build(OoStr src, OoStr out_bin);\n");
        }
        s.push('\n');
        s.push_str(&self.prelude);
        for f in &self.functions {
            s.push_str(f);
            s.push('\n');
        }
        s.push_str(&self.body);
        s
    }


    fn c_ty(&self, t: &Type) -> String {
        let resolved = t.resolve_alias(&self.type_aliases);
        match &resolved {
            Type::Int | Type::Float => "long long".into(),
            Type::Bool => "int".into(),
            Type::Void => "void".into(),
            Type::String => "OoStr".into(),
            Type::FsCap | Type::EnvCap | Type::SysCap | Type::NetCap => "int".into(),
            Type::List(inner) => match **inner {
                Type::Int => "OoIList".into(),
                Type::String => "OoSList".into(),
                _ => "OoIList".into(),
            },
            Type::Result(_, _) => "OoResS".into(),
            Type::Option(_) => "OoResS".into(),
            Type::Struct { name: Some(n), .. } => format!("struct {}", n),
            Type::Struct { name: None, .. } => "/*anon*/ int".into(),
            Type::Custom(s) => {
                if self.structs.contains_key(s) {
                    format!("struct {}", s)
                } else {
                    match s.as_str() {
                        "Int" | "Float" => "long long".into(),
                        "Bool" => "int".into(),
                        "String" => "OoStr".into(),
                        "Void" => "void".into(),
                        _ => format!("struct {}", s),
                    }
                }
            }
        }
    }


    fn emit_program(&mut self, program: &Program) -> Result<()> {
        self.type_aliases = program.collect_type_aliases();
        for item in &program.items {
            if let Item::TypeAlias(name, Type::Struct { fields, .. }) = item {
                self.structs.insert(name.clone(), fields.clone());
                let mut decl = format!("struct {} {{\n", name);
                for (fnm, fty) in fields {
                    decl.push_str(&format!("  {} {};\n", self.c_ty(fty), fnm));
                }
                decl.push_str("};\n");
                self.prelude.push_str(&decl);
            }
        }
        // forward decls
        for item in &program.items {
            if let Item::Function(f) = item {
                let ret = self.c_ty(&f.return_type);
                self.fn_ret.insert(f.name.clone(), ret.clone());
                let mut params = Vec::new();
                for p in &f.params {
                    // Keep cap params as int tokens so call-sites stay arity-correct.
                    params.push(format!("{} {}", self.c_ty(&p.param_type), p.name));
                }
                if f.name == "main" {
                    // real C main below
                    continue;
                }
                self.prelude.push_str(&format!(
                    "{} oo_{}({});\n",
                    ret,
                    f.name,
                    if params.is_empty() {
                        "void".into()
                    } else {
                        params.join(", ")
                    }
                ));
            }
        }
        for item in &program.items {
            if let Item::Function(f) = item {
                if f.name == "main" {
                    self.emit_main(f)?;
                } else {
                    self.emit_function(f)?;
                }
            }
        }
        Ok(())
    }


    fn emit_function(&mut self, f: &FunctionDecl) -> Result<()> {
        self.c_main = false;
        self.fn_void = matches!(f.return_type, Type::Void);
        let ret = self.c_ty(&f.return_type);
        let mut params = Vec::new();
        let mut env = HashMap::new();
        for p in &f.params {
            params.push(format!("{} {}", self.c_ty(&p.param_type), p.name));
            let env_ty = match &p.param_type {
                Type::FsCap | Type::EnvCap | Type::SysCap | Type::NetCap => "/*cap*/".into(),
                other => self.c_ty(other),
            };
            env.insert(p.name.clone(), env_ty);
        }
        let mut code = format!(
            "{} oo_{}({}) {{\n",
            ret,
            f.name,
            if params.is_empty() {
                "void".into()
            } else {
                params.join(", ")
            }
        );
        code.push_str(&self.emit_block(&f.body, &mut env, &f.return_type, true)?);
        if matches!(f.return_type, Type::Void) {
            code.push_str("  return;\n");
        }
        code.push_str("}\n");
        self.functions.push(code);
        Ok(())
    }

}
