#!/usr/bin/env bash
# job: pure Int-domain contract fuzz harness (no Python)
# in:  OODA_TEST_SRC, OODA_TEST_HARNESS, OODA_TEST_FUZZ_ITERS, OODA_TEST_FUZZ_SEED
#      optional OODA_TEST_FUZZ_VERBOSE=1
# out: writes harness .oo; exit 0 on success; exit 2 fail-closed unsupported
# markers (source):
#   // FUZZ_DOMAIN: int
#   // FUZZ_TARGET: <fn> <min> <max>     (single Int param; may repeat)
#   // FUZZ_REQUIRES: <fn> <expr with x>
#   // FUZZ_ENSURES: <fn> <expr with x and/or result>
set -euo pipefail

SRC="${OODA_TEST_SRC:?OODA_TEST_SRC}"
OUT="${OODA_TEST_HARNESS:?OODA_TEST_HARNESS}"
ITERS="${OODA_TEST_FUZZ_ITERS:-100}"
SEED="${OODA_TEST_FUZZ_SEED:-42}"
VERBOSE="${OODA_TEST_FUZZ_VERBOSE:-0}"

if [[ ! -f "$SRC" ]]; then
  echo "ERR	fuzz	unreadable file: $SRC" >&2
  exit 2
fi
if ! [[ "$ITERS" =~ ^[0-9]+$ ]] || [[ "$ITERS" -le 0 ]]; then
  echo "ERR	fuzz	invalid iterations: $ITERS" >&2
  exit 2
fi
if ! [[ "$SEED" =~ ^-?[0-9]+$ ]]; then
  echo "ERR	fuzz	invalid seed: $SEED" >&2
  exit 2
fi

if ! grep -qE '^[[:space:]]*//[[:space:]]*FUZZ_DOMAIN:[[:space:]]*int[[:space:]]*$' "$SRC"; then
  echo "ERR	fuzz	pure path supports only // FUZZ_DOMAIN: int fixtures (fail-closed)" >&2
  exit 2
fi

# Collect targets: name min max
mapfile -t TARGET_LINES < <(grep -E '^[[:space:]]*//[[:space:]]*FUZZ_TARGET:' "$SRC" || true)
if [[ ${#TARGET_LINES[@]} -eq 0 ]]; then
  echo "ERR	fuzz	FUZZ_DOMAIN int but no // FUZZ_TARGET: name min max" >&2
  exit 2
fi

TARGETS=()
MINS=()
MAXS=()
for line in "${TARGET_LINES[@]}"; do
  # // FUZZ_TARGET: name min max
  rest="${line#*FUZZ_TARGET:}"
  rest="${rest#"${rest%%[![:space:]]*}"}"
  # shellcheck disable=SC2086
  set -- $rest
  if [[ $# -lt 3 ]]; then
    echo "ERR	fuzz	bad FUZZ_TARGET (need name min max): $line" >&2
    exit 2
  fi
  tname="$1"
  tmin="$2"
  tmax="$3"
  if ! [[ "$tmin" =~ ^-?[0-9]+$ && "$tmax" =~ ^-?[0-9]+$ ]]; then
    echo "ERR	fuzz	FUZZ_TARGET min/max must be ints: $line" >&2
    exit 2
  fi
  if [[ "$tmin" -gt "$tmax" ]]; then
    echo "ERR	fuzz	FUZZ_TARGET min > max: $line" >&2
    exit 2
  fi
  TARGETS+=("$tname")
  MINS+=("$tmin")
  MAXS+=("$tmax")
done

# requires/ensures keyed by fn name (last wins if multiple)
declare -A REQ_EXPR=()
declare -A ENS_EXPR=()
while IFS= read -r line; do
  rest="${line#*FUZZ_REQUIRES:}"
  rest="${rest#"${rest%%[![:space:]]*}"}"
  # shellcheck disable=SC2086
  set -- $rest
  [[ $# -lt 2 ]] && continue
  fn="$1"
  shift
  REQ_EXPR["$fn"]="$*"
done < <(grep -E '^[[:space:]]*//[[:space:]]*FUZZ_REQUIRES:' "$SRC" || true)

while IFS= read -r line; do
  rest="${line#*FUZZ_ENSURES:}"
  rest="${rest#"${rest%%[![:space:]]*}"}"
  # shellcheck disable=SC2086
  set -- $rest
  [[ $# -lt 2 ]] && continue
  fn="$1"
  shift
  ENS_EXPR["$fn"]="$*"
done < <(grep -E '^[[:space:]]*//[[:space:]]*FUZZ_ENSURES:' "$SRC" || true)

# Emit body functions: strip markers, requires/ensures, and main
body_tmp="$(mktemp "${TMPDIR:-/tmp}/ooda_fuzz_body.XXXXXX")"
cleanup_body() { rm -f "$body_tmp"; }
trap cleanup_body EXIT

awk '
  function brace_delta(s,   i, c, d) {
    d = 0
    for (i = 1; i <= length(s); i++) {
      c = substr(s, i, 1)
      if (c == "{") d++
      if (c == "}") d--
    }
    return d
  }
  BEGIN { in_main = 0; depth = 0; main_seen_brace = 0 }
  /^[[:space:]]*\/\/[[:space:]]*FUZZ_/ { next }
  /^[[:space:]]*requires[[:space:]]/ { next }
  /^[[:space:]]*ensures[[:space:]]/ { next }
  !in_main && /^(pub[[:space:]]+)?fn[[:space:]]+main[[:space:]]*\(/ {
    in_main = 1
    depth = 0
    main_seen_brace = 0
  }
  in_main {
    d = brace_delta($0)
    if (d != 0 || index($0, "{") || index($0, "}")) {
      main_seen_brace = 1
      depth += d
      if (main_seen_brace && depth <= 0) {
        in_main = 0
        depth = 0
        main_seen_brace = 0
      }
    }
    next
  }
  { print }
' "$SRC" >"$body_tmp"

# Drop trailing blank noise; ensure at least one non-main fn remains
if ! grep -qE '^(pub[[:space:]]+)?fn[[:space:]]+' "$body_tmp"; then
  echo "ERR	fuzz	no non-main functions to fuzz in $SRC" >&2
  exit 2
fi

{
  echo "// generated by ooda_fuzz_pure.sh (pure int domain; no Python)"
  echo ""
  cat "$body_tmp"
  echo ""
  cat <<'OO'
pub fn prng_step(__fuzz_st: Int) -> Int {
    let mut __fuzz_s = __fuzz_st;
    if __fuzz_s == 0 {
        __fuzz_s = 42;
    }
    let __fuzz_raw = __fuzz_s * 1103515245 + 12345;
    let __fuzz_next_st = __fuzz_raw - (__fuzz_raw / 2147483648) * 2147483648;
    if __fuzz_next_st < 0 {
        return 0 - __fuzz_next_st;
    }
    return __fuzz_next_st;
}

pub fn gen_int_val(__fuzz_st: Int, __fuzz_min_v: Int, __fuzz_max_v: Int) -> Int {
    let __fuzz_abs_raw = prng_step(__fuzz_st);
    let __fuzz_span = __fuzz_max_v - __fuzz_min_v + 1;
    if __fuzz_span <= 0 {
        return __fuzz_min_v;
    }
    let __fuzz_rem = __fuzz_abs_raw - (__fuzz_abs_raw / __fuzz_span) * __fuzz_span;
    return __fuzz_min_v + __fuzz_rem;
}
OO
  echo ""
  echo "pub fn main() {"
  echo "    println(\"openOODA Fuzzer pure int domain running...\");"
  echo "    let mut __fuzz_prng_st = ${SEED};"
  echo "    let mut __fuzz_total_filtered = 0;"

  ti=0
  for fname in "${TARGETS[@]}"; do
    tmin="${MINS[$ti]}"
    tmax="${MAXS[$ti]}"
    req="${REQ_EXPR[$fname]:-}"
    ens="${ENS_EXPR[$fname]:-}"
    # rewrite markers: x -> arg, result -> res
    req_chk=""
    ens_chk=""
    if [[ -n "$req" ]]; then
      req_chk="$(echo "$req" | sed 's/\bx\b/__fuzz_x/g')"
    fi
    if [[ -n "$ens" ]]; then
      ens_chk="$(echo "$ens" | sed 's/\bresult\b/__fuzz_r/g; s/\bx\b/__fuzz_x/g')"
    fi

    echo "    let mut __fuzz_comp_${fname} = 0;"
    echo "    let mut __fuzz_cons_filt_${fname} = 0;"
    echo "    while __fuzz_comp_${fname} < ${ITERS} {"
    echo "        __fuzz_prng_st = prng_step(__fuzz_prng_st);"
    echo "        let __fuzz_x: Int = gen_int_val(__fuzz_prng_st, ${tmin}, ${tmax});"

    if [[ -n "$req_chk" ]]; then
      echo "        let __fuzz_req_ok: Bool = (${req_chk});"
      echo "        if !__fuzz_req_ok {"
      echo "            __fuzz_total_filtered = __fuzz_total_filtered + 1;"
      echo "            __fuzz_cons_filt_${fname} = __fuzz_cons_filt_${fname} + 1;"
      echo "            if __fuzz_cons_filt_${fname} >= 2000 {"
      echo "                println(\"ERR: could not satisfy precondition for function '${fname}'\");"
      echo "                println(\"FUZZ_FAIL: could not satisfy precondition\");"
      echo "                process_exit(1);"
      echo "            }"
      echo "        } else {"
      echo "            __fuzz_cons_filt_${fname} = 0;"
      echo "            __fuzz_comp_${fname} = __fuzz_comp_${fname} + 1;"
      echo "            let __fuzz_r: Int = ${fname}(__fuzz_x);"
      if [[ -n "$ens_chk" ]]; then
        echo "            let __fuzz_ens_ok: Bool = (${ens_chk});"
        echo "            if !__fuzz_ens_ok {"
        echo "                println(\"FUZZ_FAIL: postcondition failed\");"
        echo "                println(\"Function: ${fname}\");"
        echo "                process_exit(1);"
        echo "            }"
      fi
      if [[ "$VERBOSE" == "1" ]]; then
        echo "            println(\"PASS ${fname}\");"
      fi
      echo "        }"
    else
      echo "        __fuzz_comp_${fname} = __fuzz_comp_${fname} + 1;"
      echo "        let __fuzz_r: Int = ${fname}(__fuzz_x);"
      if [[ -n "$ens_chk" ]]; then
        echo "        let __fuzz_ens_ok: Bool = (${ens_chk});"
        echo "        if !__fuzz_ens_ok {"
        echo "            println(\"FUZZ_FAIL: postcondition failed\");"
        echo "            println(\"Function: ${fname}\");"
        echo "            process_exit(1);"
        echo "        }"
      fi
      if [[ "$VERBOSE" == "1" ]]; then
        echo "        println(\"PASS ${fname}\");"
      fi
    fi
    echo "    }"
    ti=$((ti + 1))
  done

  echo "    println(\"openOODA Fuzzer pure int domain passed\");"
  echo "}"
} >"$OUT"

echo "OK	fuzz	pure int harness ${#TARGETS[@]} target(s) iters=${ITERS} seed=${SEED}" >&2
exit 0
