#!/usr/bin/env python3
"""Emit fuzzer harness for openOODA contract fuzzing."""
from __future__ import annotations
import re

def emit_fuzz_harness(
    fns: list[str],
    fuzz_targets: list[dict],
    has_contracts: bool,
    fuzz_iters: int,
    fuzz_seed: int,
    fuzz_verbose: bool,
) -> str:
    parts = ["// generated by ooda_test_harness.py (fuzz mode)\n\n"]
    for f in fns:
        parts.append(f if f.endswith("\n") else f + "\n")

    parts.append("""
pub fn prng_step(__fuzz_st: Int) -> Int {
    let mut __fuzz_s = __fuzz_st;
    if __fuzz_s == 0 { __fuzz_s = 42; }
    let __fuzz_raw = __fuzz_s * 1103515245 + 12345;
    let __fuzz_next_st = __fuzz_raw - (__fuzz_raw / 2147483648) * 2147483648;
    if __fuzz_next_st < 0 { return -__fuzz_next_st; }
    return __fuzz_next_st;
}

pub fn gen_int_val(__fuzz_st: Int, __fuzz_min_v: Int, __fuzz_max_v: Int) -> Int {
    let __fuzz_abs_raw = prng_step(__fuzz_st);
    let __fuzz_choice = __fuzz_abs_raw - (__fuzz_abs_raw / 10) * 10;
    if __fuzz_choice == 0 { return __fuzz_min_v; }
    if __fuzz_choice == 1 { return __fuzz_max_v; }
    if __fuzz_choice == 2 && __fuzz_min_v <= 0 && __fuzz_max_v >= 0 { return 0; }
    let __fuzz_span = __fuzz_max_v - __fuzz_min_v + 1;
    if __fuzz_span <= 0 { return __fuzz_min_v; }
    let __fuzz_rem = __fuzz_abs_raw - (__fuzz_abs_raw / __fuzz_span) * __fuzz_span;
    return __fuzz_min_v + __fuzz_rem;
}

pub fn gen_bool_val(__fuzz_st: Int) -> Bool {
    let __fuzz_abs_raw = prng_step(__fuzz_st);
    let __fuzz_v = __fuzz_abs_raw - (__fuzz_abs_raw / 2) * 2;
    return __fuzz_v != 0;
}

pub fn gen_string_val(__fuzz_st: Int, __fuzz_max_len: Int) -> String {
    let __fuzz_abs_raw = prng_step(__fuzz_st);
    let __fuzz_mod_span = __fuzz_max_len + 1;
    let __fuzz_len = __fuzz_abs_raw - (__fuzz_abs_raw / __fuzz_mod_span) * __fuzz_mod_span;
    let __fuzz_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    let __fuzz_num_chars = chars_len(__fuzz_chars);
    let mut __fuzz_out_str = "";
    let mut __fuzz_i = 0;
    let mut __fuzz_cur_st = __fuzz_abs_raw;
    while __fuzz_i < __fuzz_len {
        __fuzz_cur_st = prng_step(__fuzz_cur_st);
        let __fuzz_idx = __fuzz_cur_st - (__fuzz_cur_st / __fuzz_num_chars) * __fuzz_num_chars;
        __fuzz_out_str = __fuzz_out_str + char_at(__fuzz_chars, __fuzz_idx);
        __fuzz_i = __fuzz_i + 1;
    }
    return __fuzz_out_str;
}

pub fn gen_list_int_val(__fuzz_st: Int, __fuzz_max_len: Int, __fuzz_min_v: Int, __fuzz_max_v: Int) -> List[Int] {
    let __fuzz_abs_raw = prng_step(__fuzz_st);
    let __fuzz_mod_span = __fuzz_max_len + 1;
    let __fuzz_len = __fuzz_abs_raw - (__fuzz_abs_raw / __fuzz_mod_span) * __fuzz_mod_span;
    let mut __fuzz_lst: List[Int] = list_new();
    let mut __fuzz_i = 0;
    let mut __fuzz_cur_st = __fuzz_abs_raw;
    while __fuzz_i < __fuzz_len {
        __fuzz_cur_st = prng_step(__fuzz_cur_st);
        __fuzz_lst = list_push(__fuzz_lst, gen_int_val(__fuzz_cur_st, __fuzz_min_v, __fuzz_max_v));
        __fuzz_i = __fuzz_i + 1;
    }
    return __fuzz_lst;
}

pub fn list_int_to_str(__fuzz_xs: List[Int]) -> String {
    let __fuzz_n = list_len(__fuzz_xs);
    let mut __fuzz_out = "[";
    let mut __fuzz_i = 0;
    while __fuzz_i < __fuzz_n {
        if __fuzz_i > 0 { __fuzz_out = __fuzz_out + ", "; }
        __fuzz_out = __fuzz_out + list_get(__fuzz_xs, __fuzz_i).to_string();
        __fuzz_i = __fuzz_i + 1;
    }
    return __fuzz_out + "]";
}
""")

    parts.append("\npub fn main() {\n")
    parts.append("    println(\"🚀 [openOODA Fuzzer] Running contract fuzzing...\");\n")
    if not has_contracts:
        parts.append("    println(\"WARNING: no contracts found in source file\");\n")

    parts.append(f"    let mut __fuzz_prng_st = {fuzz_seed};\n")
    parts.append("    let mut __fuzz_total_filtered = 0;\n")

    for target in fuzz_targets:
        fname = target['fname']
        params = target['params']
        req_clauses = target['requires']
        ens_clauses = target['ensures']
        ret_type = target['return_type']

        parts.append(f"    let mut __fuzz_comp_{fname} = 0;\n")
        parts.append(f"    let mut __fuzz_cons_filt_{fname} = 0;\n")
        parts.append(f"    while __fuzz_comp_{fname} < {fuzz_iters} {{\n")

        param_vars = []
        for idx, (pname, ptype) in enumerate(params):
            vname = f"__fuzz_arg_{fname}_{idx}"
            param_vars.append(vname)
            parts.append("        __fuzz_prng_st = prng_step(__fuzz_prng_st);\n")
            if ptype == "Int":
                parts.append(f"        let {vname}: Int = gen_int_val(__fuzz_prng_st, -1000, 1000);\n")
            elif ptype == "String":
                parts.append(f"        let {vname}: String = gen_string_val(__fuzz_prng_st, 16);\n")
            elif ptype == "Bool":
                parts.append(f"        let {vname}: Bool = gen_bool_val(__fuzz_prng_st);\n")
            elif ptype == "List[Int]":
                parts.append(f"        let {vname}: List[Int] = gen_list_int_val(__fuzz_prng_st, 8, -100, 100);\n")
            else:
                parts.append(f"        let {vname}: Int = 0;\n")

        if req_clauses:
            req_exprs = []
            for req in req_clauses:
                expr = req
                for idx, (pname, ptype) in enumerate(params):
                    vname = f"__fuzz_arg_{fname}_{idx}"
                    expr = re.sub(r'\b' + re.escape(pname) + r'\b', vname, expr)
                req_exprs.append(f"({expr})")
            req_check = " && ".join(req_exprs)

            parts.append(f"        let __fuzz_req_ok: Bool = {req_check};\n")
            parts.append("        if !__fuzz_req_ok {\n")
            parts.append("            __fuzz_total_filtered = __fuzz_total_filtered + 1;\n")
            parts.append(f"            __fuzz_cons_filt_{fname} = __fuzz_cons_filt_{fname} + 1;\n")
            parts.append(f"            if __fuzz_cons_filt_{fname} >= 2000 {{\n")
            parts.append(f'                println("ERR: could not satisfy precondition for function \'{fname}\'");\n')
            parts.append('                println("FUZZ_FAIL: could not satisfy precondition");\n')
            parts.append("                process_exit(1);\n")
            parts.append("            }\n")
            parts.append("        } else {\n")
            indent = "            "
        else:
            indent = "        "

        parts.append(indent + f"__fuzz_cons_filt_{fname} = 0;\n")
        parts.append(indent + f"__fuzz_comp_{fname} = __fuzz_comp_{fname} + 1;\n")

        args_joined = ", ".join(param_vars)
        if ret_type != "()":
            parts.append(indent + f"let __fuzz_res: {ret_type} = {fname}({args_joined});\n")
        else:
            parts.append(indent + f"{fname}({args_joined});\n")

        if ens_clauses:
            ens_exprs = []
            for ens in ens_clauses:
                ens_expr = ens
                ens_expr = re.sub(r'\bresult\b', '__fuzz_res', ens_expr)
                for idx, (pname, ptype) in enumerate(params):
                    vname = f"__fuzz_arg_{fname}_{idx}"
                    ens_expr = re.sub(r'\b' + re.escape(pname) + r'\b', vname, ens_expr)
                ens_exprs.append(f"({ens_expr})")

            combined_ens = " && ".join(ens_exprs)
            ens_joined_text = " && ".join(ens_clauses)

            parts.append(indent + f"let __fuzz_ens_ok: Bool = {combined_ens};\n")
            parts.append(indent + "if !__fuzz_ens_ok {\n")
            parts.append(indent + '    println("FUZZ_FAIL: postcondition failed");\n')
            parts.append(indent + f'    println("Function: {fname}");\n')
            parts.append(indent + f'    println("Iteration: " + __fuzz_comp_{fname}.to_string() + " (seed: {fuzz_seed})");\n')
            parts.append(indent + f'    println("Violation: ensures {ens_joined_text} evaluated to false");\n')
            parts.append(indent + '    println("Counterexample:");\n')

            for idx, (pname, ptype) in enumerate(params):
                vname = f"__fuzz_arg_{fname}_{idx}"
                if ptype == "Int":
                    parts.append(indent + f'    println("  {pname} = " + {vname}.to_string());\n')
                elif ptype == "Bool":
                    parts.append(indent + f'    let __fuzz_arg_str_{idx}: String = if {vname} {{ "true" }} else {{ "false" }};\n')
                    parts.append(indent + f'    println("  {pname} = " + __fuzz_arg_str_{idx});\n')
                elif ptype == "String":
                    parts.append(indent + f'    println("  {pname} = \\"" + {vname} + "\\"");\n')
                elif ptype == "List[Int]":
                    parts.append(indent + f'    let __fuzz_arg_str_{idx}: String = list_int_to_str({vname});\n')
                    parts.append(indent + f'    println("  {pname} = " + __fuzz_arg_str_{idx});\n')
                else:
                    parts.append(indent + f'    println("  {pname} = <val>");\n')

            parts.append(indent + "    process_exit(1);\n")
            parts.append(indent + "}\n")

        if fuzz_verbose:
            parts.append(indent + f'println("Iter " + __fuzz_comp_{fname}.to_string() + ": PASS");\n')

        if req_clauses:
            parts.append("        }\n")

        parts.append("    }\n")

    parts.append(f'    println("🚀 [openOODA Fuzzer] {fuzz_iters} iterations | Filtered " + __fuzz_total_filtered.to_string() + " | 0 violations | Fuzz test passed");\n')
    parts.append("}\n")

    return "".join(parts)
