// ===================================================================
// CHS → C backend (native stage-1 path without clang).
// Emits ISO C99 + runtime/chs_rt.c, linked with gcc.
// ===================================================================
use crate::ast::*;
use anyhow::{bail, Result};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::process::Command;

pub struct CCodeGen;

impl CCodeGen {
    pub fn emit_c(program: &Program) -> Result<String> {
        Self::assert_chs_c_subset(program)?;
        let mut g = Gen::new();
        g.emit_program(program)?;
        Ok(g.finish())
    }

    fn assert_chs_c_subset(program: &Program) -> Result<()> {
        for item in &program.items {
            if let Item::Function(f) = item {
                for p in &f.params {
                    Self::check_ty(&p.param_type, &f.name)?;
                }
                Self::check_ty(&f.return_type, &f.name)?;
            }
        }
        Ok(())
    }

    fn check_ty(t: &Type, ctx: &str) -> Result<()> {
        match t {
            Type::Int | Type::Bool | Type::Void | Type::String | Type::Float => Ok(()),
            Type::FsCap | Type::EnvCap | Type::SysCap | Type::NetCap => Ok(()),
            Type::List(inner) => match **inner {
                Type::Int | Type::String => Ok(()),
                _ => bail!("C backend List only supports List[Int]|List[String] in '{}'", ctx),
            },
            Type::Struct { .. } => Ok(()),
            Type::Option(_) | Type::Result(_, _) => Ok(()),
            Type::Custom(s) => match s.as_str() {
                "Int" | "Bool" | "String" | "Void" | "Float" => Ok(()),
                _ => Ok(()), // named struct aliases
            },
        }
    }

    /// Compile .oo → native binary via gcc + chs_rt.c. Returns path to binary.
    pub fn build_native(program: &Program, out_bin: &Path, rt_c: &Path) -> Result<()> {
        let c_src = Self::emit_c(program)?;
        let out_c = out_bin.with_extension("c");
        std::fs::write(&out_c, &c_src)?;
        let gcc = which_gcc()?;
        // Prefer HOME cache for compiler temp files — /tmp may be quota-limited.
        let tmp = std::env::var("TMPDIR").unwrap_or_else(|_| {
            let p = dirs_tmp();
            let _ = std::fs::create_dir_all(&p);
            p
        });
        let out = Command::new(&gcc)
            .env("TMPDIR", &tmp)
            .env("TMP", &tmp)
            .env("TEMP", &tmp)
            .arg("-O2")
            .arg("-std=c99")
            .arg(&out_c)
            .arg(rt_c)
            .arg("-o")
            .arg(out_bin)
            .output()
            .map_err(|e| anyhow::anyhow!("failed to spawn {}: {}", gcc, e))?;
        if !out.status.success() {
            let err = String::from_utf8_lossy(&out.stderr);
            bail!("gcc failed linking CHS C backend:\n{}", err.chars().take(800).collect::<String>());
        }
        Ok(())
    }
}

fn c_escape_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\x{:02x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

fn which_gcc() -> Result<String> {
    for t in ["gcc", "cc"] {
        if Command::new(t).arg("--version").output().map(|o| o.status.success()).unwrap_or(false) {
            return Ok(t.into());
        }
    }
    bail!("no gcc/cc in PATH for CHS C backend native link")
}

fn dirs_tmp() -> String {
    if let Ok(h) = std::env::var("HOME") {
        format!("{}/.cache/ooda-tmp", h)
    } else {
        "/var/tmp".into()
    }
}

struct Gen {
    structs: HashMap<String, Vec<(String, Type)>>,
    /// name → C return type string
    fn_ret: HashMap<String, String>,
    functions: Vec<String>,
    prelude: String,
    body: String,
    tmp: usize,
    /// When true, bare `return;` becomes `return 0;` (C main).
    c_main: bool,
    /// Current OODA function returns void (bare return;).
    fn_void: bool,
}

impl Gen {
    fn new() -> Self {
        Self {
            structs: HashMap::new(),
            fn_ret: HashMap::new(),
            functions: Vec::new(),
            prelude: String::new(),
            body: String::new(),
            tmp: 0,
            c_main: false,
            fn_void: false,
        }
    }

    fn fresh(&mut self, p: &str) -> String {
        self.tmp += 1;
        format!("{}_{}", p, self.tmp)
    }

    fn finish(self) -> String {
        let mut s = String::new();
        s.push_str("/* generated by openOODA CHS C backend — do not edit */\n");
        s.push_str("#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n#include <stdbool.h>\n");
        s.push_str("/* runtime decls (defined in chs_rt.c) */\n");
        s.push_str("typedef struct { char *data; long long len; } OoStr;\n");
        s.push_str("typedef struct { long long *data; long long len; long long cap; } OoIList;\n");
        s.push_str("typedef struct { OoStr *data; long long len; long long cap; } OoSList;\n");
        s.push_str("typedef struct { int ok; OoStr val; } OoResS;\n");
        s.push_str("typedef struct { int ok; OoStr err; } OoResV;\n");
        s.push_str("OoStr oo_str_lit(const char*); OoStr oo_str_concat(OoStr,OoStr);\n");
        s.push_str("long long oo_str_byte_len(OoStr); long long oo_chars_len(OoStr);\n");
        s.push_str("OoStr oo_char_at(OoStr,long long); OoStr oo_str_slice(OoStr,long long,long long);\n");
        s.push_str("int oo_char_is_digit(OoStr); int oo_char_is_alpha(OoStr); int oo_char_is_space(OoStr);\n");
        s.push_str("OoIList oo_ilist_new(void); OoIList oo_ilist_push(OoIList,long long);\n");
        s.push_str("long long oo_ilist_get(OoIList,long long); long long oo_ilist_len(OoIList);\n");
        s.push_str("OoSList oo_slist_new(void); OoSList oo_slist_push(OoSList,OoStr);\n");
        s.push_str("OoStr oo_slist_get(OoSList,long long); long long oo_slist_len(OoSList);\n");
        s.push_str("OoResS oo_read_file(OoStr); OoResV oo_write_file(OoStr,OoStr);\n");
        s.push_str("void oo_print_str(OoStr); void oo_print_int(long long); void oo_print_bool(int); void oo_println(void);\n");
        s.push_str("int oo_str_eq(OoStr,OoStr);\n\n");
        s.push_str(&self.prelude);
        for f in &self.functions {
            s.push_str(f);
            s.push('\n');
        }
        s.push_str(&self.body);
        s
    }

    fn c_ty(&self, t: &Type) -> String {
        match t {
            Type::Int | Type::Float => "long long".into(),
            Type::Bool => "int".into(),
            Type::Void => "void".into(),
            Type::String => "OoStr".into(),
            Type::FsCap | Type::EnvCap | Type::SysCap | Type::NetCap => "int".into(),
            Type::List(inner) => match **inner {
                Type::Int => "OoIList".into(),
                Type::String => "OoSList".into(),
                _ => "OoIList".into(),
            },
            Type::Result(_, _) => "OoResS".into(),
            Type::Option(_) => "OoResS".into(),
            Type::Struct { name: Some(n), .. } => format!("struct {}", n),
            Type::Struct { name: None, .. } => "/*anon*/ int".into(),
            Type::Custom(s) => {
                if self.structs.contains_key(s) {
                    format!("struct {}", s)
                } else {
                    match s.as_str() {
                        "Int" | "Float" => "long long".into(),
                        "Bool" => "int".into(),
                        "String" => "OoStr".into(),
                        "Void" => "void".into(),
                        _ => format!("struct {}", s),
                    }
                }
            }
        }
    }

    fn emit_program(&mut self, program: &Program) -> Result<()> {
        for item in &program.items {
            if let Item::TypeAlias(name, Type::Struct { fields, .. }) = item {
                self.structs.insert(name.clone(), fields.clone());
                let mut decl = format!("struct {} {{\n", name);
                for (fnm, fty) in fields {
                    decl.push_str(&format!("  {} {};\n", self.c_ty(fty), fnm));
                }
                decl.push_str("};\n");
                self.prelude.push_str(&decl);
            }
        }
        // forward decls
        for item in &program.items {
            if let Item::Function(f) = item {
                let ret = self.c_ty(&f.return_type);
                self.fn_ret.insert(f.name.clone(), ret.clone());
                let mut params = Vec::new();
                for p in &f.params {
                    // Keep cap params as int tokens so call-sites stay arity-correct.
                    params.push(format!("{} {}", self.c_ty(&p.param_type), p.name));
                }
                if f.name == "main" {
                    // real C main below
                    continue;
                }
                self.prelude.push_str(&format!(
                    "{} oo_{}({});\n",
                    ret,
                    f.name,
                    if params.is_empty() {
                        "void".into()
                    } else {
                        params.join(", ")
                    }
                ));
            }
        }
        for item in &program.items {
            if let Item::Function(f) = item {
                if f.name == "main" {
                    self.emit_main(f)?;
                } else {
                    self.emit_function(f)?;
                }
            }
        }
        Ok(())
    }

    fn emit_function(&mut self, f: &FunctionDecl) -> Result<()> {
        self.c_main = false;
        self.fn_void = matches!(f.return_type, Type::Void);
        let ret = self.c_ty(&f.return_type);
        let mut params = Vec::new();
        let mut env = HashMap::new();
        for p in &f.params {
            params.push(format!("{} {}", self.c_ty(&p.param_type), p.name));
            env.insert(p.name.clone(), self.c_ty(&p.param_type));
        }
        let mut code = format!(
            "{} oo_{}({}) {{\n",
            ret,
            f.name,
            if params.is_empty() {
                "void".into()
            } else {
                params.join(", ")
            }
        );
        code.push_str(&self.emit_block(&f.body, &mut env, &f.return_type, true)?);
        if matches!(f.return_type, Type::Void) {
            code.push_str("  return;\n");
        }
        code.push_str("}\n");
        self.functions.push(code);
        Ok(())
    }

    fn emit_main(&mut self, f: &FunctionDecl) -> Result<()> {
        self.c_main = true;
        self.fn_void = false;
        let mut env = HashMap::new();
        let mut code = String::from("int main(int argc, char **argv) {\n");
        // inject caps as dummy ints
        for p in &f.params {
            match &p.param_type {
                Type::FsCap | Type::EnvCap | Type::SysCap | Type::NetCap => {
                    code.push_str(&format!("  int {} = 1; /* capability token */\n", p.name));
                    env.insert(p.name.clone(), "int".into());
                }
                Type::List(inner) if matches!(**inner, Type::String) || p.name == "args" || p.name == "argv" => {
                    code.push_str("  OoSList args = oo_slist_new();\n");
                    code.push_str("  for (int i = 1; i < argc; i++) {\n");
                    code.push_str("    args = oo_slist_push(args, oo_str_lit(argv[i]));\n");
                    code.push_str("  }\n");
                    // also bind param name if not args
                    if p.name != "args" {
                        code.push_str(&format!("  OoSList {} = args;\n", p.name));
                    }
                    env.insert(p.name.clone(), "OoSList".into());
                }
                other => {
                    code.push_str(&format!(
                        "  {} {} = {{0}}; /* default main param */\n",
                        self.c_ty(other),
                        p.name
                    ));
                    env.insert(p.name.clone(), self.c_ty(other));
                }
            }
        }
        // Use Int return type so `return;` in OODA main becomes `return 0;` in C.
        code.push_str(&self.emit_block(&f.body, &mut env, &Type::Int, true)?);
        code.push_str("  return 0;\n}\n");
        self.body.push_str(&code);
        Ok(())
    }

    fn emit_block(
        &mut self,
        block: &Block,
        env: &mut HashMap<String, String>,
        ret_ty: &Type,
        tail_is_fn_return: bool,
    ) -> Result<String> {
        let mut code = String::new();
        for stmt in &block.stmts {
            code.push_str(&self.emit_stmt(stmt, env, ret_ty)?);
        }
        if let Some(e) = &block.expr {
            let (c, v, ty) = self.emit_expr(e, env)?;
            code.push_str(&c);
            // Only function bodies should turn a trailing expression into `return`.
            // while/if bodies often end with a trailing `if` expression.
            if tail_is_fn_return && !matches!(ret_ty, Type::Void) {
                code.push_str(&format!("  return {};\n", v));
            } else {
                let _ = (ty, v);
            }
        }
        Ok(code)
    }

    fn emit_stmt(
        &mut self,
        stmt: &Statement,
        env: &mut HashMap<String, String>,
        ret_ty: &Type,
    ) -> Result<String> {
        match stmt {
            Statement::Let {
                name,
                type_annotation,
                init,
                ..
            } => {
                let (c, v, ty) = self.emit_expr(init, env)?;
                let cty = type_annotation
                    .as_ref()
                    .map(|t| self.c_ty(t))
                    .unwrap_or(ty);
                env.insert(name.clone(), cty.clone());
                Ok(format!("{}  {} {} = {};\n", c, cty, name, v))
            }
            Statement::Assign { name, value, .. } => {
                let (c, v, _) = self.emit_expr(value, env)?;
                Ok(format!("{}  {} = {};\n", c, name, v))
            }
            Statement::Return(Some(e), _) => {
                let (c, v, _) = self.emit_expr(e, env)?;
                match ret_ty {
                    Type::Void => Ok(format!("{}  return;\n", c)),
                    Type::Custom(s) if s == "_ret" => {
                        // Nested in if/while: emit real return value (function returns non-void).
                        Ok(format!("{}  return {};\n", c, v))
                    }
                    _ => Ok(format!("{}  return {};\n", c, v)),
                }
            }
            Statement::Return(None, _) => {
                if self.c_main {
                    Ok("  return 0;\n".into())
                } else {
                    Ok("  return;\n".into())
                }
            }
            Statement::Expr(e, _) => {
                // println and side-effecting calls
                if let Expression::Call { name, args, .. } = e {
                    if name == "println" {
                        return self.emit_println(args, env);
                    }
                }
                let (c, _v, _) = self.emit_expr(e, env)?;
                Ok(c)
            }
            Statement::While { cond, body, .. } => {
                let mut code = String::from("  while (1) {\n");
                let (cc2, cv2, _) = self.emit_expr(cond, env)?;
                code.push_str(&cc2);
                code.push_str(&format!("    if (!({})) break;\n", cv2));
                code.push_str(&self.emit_block(body, env, ret_ty, false)?);
                code.push_str("  }\n");
                Ok(code)
            }
        }
    }

    fn emit_println(&mut self, args: &[Expression], env: &mut HashMap<String, String>) -> Result<String> {
        let mut code = String::new();
        for a in args {
            let (c, v, ty) = self.emit_expr(a, env)?;
            code.push_str(&c);
            if ty == "OoStr" {
                code.push_str(&format!("  oo_print_str({});\n", v));
            } else if ty == "int" {
                code.push_str(&format!("  oo_print_bool({});\n", v));
            } else {
                code.push_str(&format!("  oo_print_int({});\n", v));
            }
        }
        code.push_str("  oo_println();\n");
        Ok(code)
    }

    fn emit_expr(
        &mut self,
        expr: &Expression,
        env: &mut HashMap<String, String>,
    ) -> Result<(String, String, String)> {
        match expr {
            Expression::Literal(Literal::Int(n), _) => {
                Ok((String::new(), format!("{}LL", n), "long long".into()))
            }
            Expression::Literal(Literal::Bool(b), _) => {
                Ok((String::new(), if *b { "1" } else { "0" }.into(), "int".into()))
            }
            Expression::Literal(Literal::String(s), _) => {
                let lit = c_escape_string(s);
                let t = self.fresh("s");
                Ok((
                    format!("  OoStr {} = oo_str_lit(\"{}\");\n", t, lit),
                    t,
                    "OoStr".into(),
                ))
            }
            Expression::Literal(Literal::Float(f), _) => {
                Ok((String::new(), format!("{}LL", *f as i64), "long long".into()))
            }
            Expression::Literal(Literal::Void, _) => {
                Ok((String::new(), "0".into(), "int".into()))
            }
            Expression::Variable(name, _) => {
                let ty = env.get(name).cloned().unwrap_or_else(|| "long long".into());
                Ok((String::new(), name.clone(), ty))
            }
            Expression::Binary { op, left, right, .. } => {
                let (lc, lv, lty) = self.emit_expr(left, env)?;
                let (rc, rv, rty) = self.emit_expr(right, env)?;
                let mut code = lc;
                code.push_str(&rc);
                if matches!(op, BinOp::Add) && (lty == "OoStr" || rty == "OoStr") {
                    let t = self.fresh("cat");
                    code.push_str(&format!(
                        "  OoStr {} = oo_str_concat({}, {});\n",
                        t, lv, rv
                    ));
                    return Ok((code, t, "OoStr".into()));
                }
                if matches!(op, BinOp::Eq | BinOp::Neq) && lty == "OoStr" {
                    let t = self.fresh("eq");
                    if matches!(op, BinOp::Eq) {
                        code.push_str(&format!("  int {} = oo_str_eq({}, {});\n", t, lv, rv));
                    } else {
                        code.push_str(&format!("  int {} = !oo_str_eq({}, {});\n", t, lv, rv));
                    }
                    return Ok((code, t, "int".into()));
                }
                let cop = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Eq => "==",
                    BinOp::Neq => "!=",
                    BinOp::Lt => "<",
                    BinOp::Lte => "<=",
                    BinOp::Gt => ">",
                    BinOp::Gte => ">=",
                    BinOp::And => "&&",
                    BinOp::Or => "||",
                    _ => bail!("C backend: unsupported binop {:?}", op),
                };
                let t = self.fresh("b");
                let rty = if matches!(
                    op,
                    BinOp::Eq | BinOp::Neq | BinOp::Lt | BinOp::Lte | BinOp::Gt | BinOp::Gte | BinOp::And | BinOp::Or
                ) {
                    "int"
                } else {
                    "long long"
                };
                code.push_str(&format!(
                    "  {} {} = ({}) {} ({});\n",
                    rty, t, lv, cop, rv
                ));
                Ok((code, t, rty.into()))
            }
            Expression::Unary { op, expr, .. } => {
                let (c, v, _) = self.emit_expr(expr, env)?;
                let t = self.fresh("u");
                let mut code = c;
                match op {
                    UnaryOp::Not => {
                        code.push_str(&format!("  int {} = !({});\n", t, v));
                        Ok((code, t, "int".into()))
                    }
                    UnaryOp::Neg => {
                        code.push_str(&format!("  long long {} = -({});\n", t, v));
                        Ok((code, t, "long long".into()))
                    }
                }
            }
            Expression::Call { name, args, .. } => self.emit_call(name, args, env),
            Expression::If {
                cond,
                then_branch,
                else_branch,
                ..
            } => {
                // Statement-style if (no value): emit control flow only.
                // Value-style if is limited to int results from tails.
                let (cc, cv, _) = self.emit_expr(cond, env)?;
                let mut code = cc;
                // Prefer statement-if when branches have returns/stmts without shared value.
                let t = self.fresh("ifv");
                code.push_str(&format!("  long long {} = 0;\n", t));
                code.push_str(&format!("  if ({}) {{\n", cv));
                // Use Unknown ret so Return(Some) still emits the value; Void would force `return 0`.
                for s in &then_branch.stmts {
                    code.push_str(&self.emit_stmt(s, env, &Type::Custom("_ret".into()))?);
                }
                if let Some(e) = &then_branch.expr {
                    let (tc, tv, tty) = self.emit_expr(e, env)?;
                    code.push_str(&tc);
                    if tty == "long long" || tty == "int" {
                        code.push_str(&format!("    {} = {};\n", t, tv));
                    }
                }
                code.push_str("  }");
                if let Some(eb) = else_branch {
                    code.push_str(" else {\n");
                    for s in &eb.stmts {
                        code.push_str(&self.emit_stmt(s, env, &Type::Custom("_ret".into()))?);
                    }
                    if let Some(e) = &eb.expr {
                        let (ec, ev, ety) = self.emit_expr(e, env)?;
                        code.push_str(&ec);
                        if ety == "long long" || ety == "int" {
                            code.push_str(&format!("    {} = {};\n", t, ev));
                        }
                    }
                    code.push_str("  }\n");
                } else {
                    code.push_str("\n");
                }
                Ok((code, t, "long long".into()))
            }
            Expression::While { .. } => {
                bail!("C backend: while as expression not supported; use statement while")
            }
            Expression::Match { expr, arms, .. } => {
                // Lower Result match: Ok/Err only, int/string payload loosely
                let (ec, ev, ety) = self.emit_expr(expr, env)?;
                let t = self.fresh("mv");
                let mut code = ec;
                if ety == "OoResS" {
                    code.push_str(&format!("  OoStr {} = oo_str_lit(\"\");\n", t));
                    code.push_str(&format!("  if (({}).ok) {{\n", ev));
                    for arm in arms {
                        if let Pattern::Variant { name, arg } = &arm.pattern {
                            if name == "Ok" {
                                if let Some(bind) = arg {
                                    code.push_str(&format!(
                                        "    OoStr {} = ({}).val;\n",
                                        bind, ev
                                    ));
                                    env.insert(bind.clone(), "OoStr".into());
                                }
                                let (bc, bv, bty) = self.emit_expr(&arm.body, env)?;
                                code.push_str(&bc);
                                if bty == "OoStr" {
                                    code.push_str(&format!("    {} = {};\n", t, bv));
                                }
                            }
                        }
                    }
                    code.push_str("  } else {\n");
                    for arm in arms {
                        if let Pattern::Variant { name, arg } = &arm.pattern {
                            if name == "Err" {
                                if let Some(bind) = arg {
                                    code.push_str(&format!(
                                        "    OoStr {} = ({}).val;\n",
                                        bind, ev
                                    ));
                                    env.insert(bind.clone(), "OoStr".into());
                                }
                                let (bc, bv, bty) = self.emit_expr(&arm.body, env)?;
                                code.push_str(&bc);
                                if bty == "OoStr" {
                                    code.push_str(&format!("    {} = {};\n", t, bv));
                                }
                            }
                        }
                    }
                    code.push_str("  }\n");
                    Ok((code, t, "OoStr".into()))
                } else {
                    // int match on scrutinee
                    code.push_str(&format!("  long long {} = 0;\n", t));
                    for arm in arms {
                        match &arm.pattern {
                            Pattern::Literal(Literal::Int(n)) => {
                                code.push_str(&format!("  if (({}) == {}LL) {{\n", ev, n));
                                let (bc, bv, _) = self.emit_expr(&arm.body, env)?;
                                code.push_str(&bc);
                                code.push_str(&format!("    {} = {};\n", t, bv));
                                code.push_str("  } else ");
                            }
                            Pattern::Wildcard => {
                                code.push_str("  {\n");
                                let (bc, bv, _) = self.emit_expr(&arm.body, env)?;
                                code.push_str(&bc);
                                code.push_str(&format!("    {} = {};\n", t, bv));
                                code.push_str("  }\n");
                            }
                            _ => {}
                        }
                    }
                    Ok((code, t, "long long".into()))
                }
            }
            Expression::StructLit { name, fields, .. } => {
                let t = self.fresh("st");
                let mut code = format!("  struct {} {} ;\n", name, t);
                for (fnm, fex) in fields {
                    let (fc, fv, _) = self.emit_expr(fex, env)?;
                    code.push_str(&fc);
                    code.push_str(&format!("  {} .{} = {};\n", t, fnm, fv));
                }
                Ok((code, t, format!("struct {}", name)))
            }
        }
    }

    fn emit_call(
        &mut self,
        name: &str,
        args: &[Expression],
        env: &mut HashMap<String, String>,
    ) -> Result<(String, String, String)> {
        // Field access .foo with one arg
        if let Some(field) = name.strip_prefix('.') {
            if args.len() == 1 {
                if field == "to_string" {
                    let (c, v, ty) = self.emit_expr(&args[0], env)?;
                    let t = self.fresh("ts");
                    let mut code = c;
                    if ty == "OoStr" {
                        code.push_str(&format!("  OoStr {} = {};\n", t, v));
                    } else if ty == "int" {
                        // bool
                        code.push_str(&format!(
                            "  OoStr {} = oo_str_lit(({}) ? \"true\" : \"false\");\n",
                            t, v
                        ));
                    } else {
                        // int → decimal via snprintf
                        let buf = self.fresh("buf");
                        code.push_str(&format!("  char {}[32];\n", buf));
                        code.push_str(&format!(
                            "  snprintf({}, sizeof({}), \"%lld\", (long long)({}));\n",
                            buf, buf, v
                        ));
                        code.push_str(&format!("  OoStr {} = oo_str_lit({});\n", t, buf));
                    }
                    return Ok((code, t, "OoStr".into()));
                }
                if field == "len" {
                    let (c, v, ty) = self.emit_expr(&args[0], env)?;
                    let t = self.fresh("ln");
                    let mut code = c;
                    if ty == "OoStr" {
                        code.push_str(&format!(
                            "  long long {} = oo_str_byte_len({});\n",
                            t, v
                        ));
                    } else if ty == "OoIList" {
                        code.push_str(&format!(
                            "  long long {} = oo_ilist_len({});\n",
                            t, v
                        ));
                    } else if ty == "OoSList" {
                        code.push_str(&format!(
                            "  long long {} = oo_slist_len({});\n",
                            t, v
                        ));
                    } else {
                        bail!(".len on unsupported type {}", ty);
                    }
                    return Ok((code, t, "long long".into()));
                }
                if field == "is_ok" || field == "is_err" {
                    let (c, v, _) = self.emit_expr(&args[0], env)?;
                    let t = self.fresh("io");
                    let mut code = c;
                    if field == "is_ok" {
                        code.push_str(&format!("  int {} = ({}).ok;\n", t, v));
                    } else {
                        code.push_str(&format!("  int {} = !({}).ok;\n", t, v));
                    }
                    return Ok((code, t, "int".into()));
                }
                // struct field
                let (c, v, ty) = self.emit_expr(&args[0], env)?;
                let t = self.fresh("fld");
                let mut code = c;
                // Guess field type from known structs
                let fty = if let Some(sname) = ty.strip_prefix("struct ") {
                    self.structs
                        .get(sname)
                        .and_then(|fs| fs.iter().find(|(n, _)| n == field))
                        .map(|(_, t)| self.c_ty(t))
                        .unwrap_or_else(|| "long long".into())
                } else {
                    "long long".into()
                };
                code.push_str(&format!("  {} {} = {}.{};\n", fty, t, v, field));
                return Ok((code, t, fty));
            }
        }

        let mut code = String::new();
        let mut cargs = Vec::new();
        let mut arg_tys = Vec::new();
        for a in args {
            // skip pure capability args for free functions
            if let Expression::Variable(n, _) = a {
                if env.get(n).map(|t| t == "int" || t == "/*cap*/").unwrap_or(false)
                    && matches!(
                        name,
                        "read_file" | "write_file" | "fs_read" | "fs_write" | "env_get"
                    )
                {
                    // still need path/content only
                }
            }
            let (c, v, ty) = self.emit_expr(a, env)?;
            code.push_str(&c);
            // Filter capability dummy ints for builtins that don't take them in C
            if ty == "int" && matches!(name, "read_file" | "write_file" | "fs_read" | "fs_write") {
                // could be cap — only skip if it's a known cap var
                if let Expression::Variable(n, _) = a {
                    if env.get(n).map(|t| t.as_str()) == Some("int")
                        && (n.contains("fs")
                            || n.contains("cap")
                            || n == "fs"
                            || n == "net"
                            || n == "sys"
                            || n == "env")
                    {
                        continue;
                    }
                }
            }
            cargs.push(v);
            arg_tys.push(ty);
        }

        let t = self.fresh("r");
        match name {
            "list_new" => {
                // default int list; if used as string list context hard — use int
                code.push_str(&format!("  OoIList {} = oo_ilist_new();\n", t));
                Ok((code, t, "OoIList".into()))
            }
            "list_push" => {
                let list = &cargs[0];
                let item = &cargs[1];
                let lty = &arg_tys[0];
                if lty == "OoSList" || arg_tys.get(1).map(|s| s.as_str()) == Some("OoStr") {
                    code.push_str(&format!(
                        "  OoSList {} = oo_slist_push({}, {});\n",
                        t, list, item
                    ));
                    Ok((code, t, "OoSList".into()))
                } else {
                    code.push_str(&format!(
                        "  OoIList {} = oo_ilist_push({}, {});\n",
                        t, list, item
                    ));
                    Ok((code, t, "OoIList".into()))
                }
            }
            "list_get" => {
                let lty = &arg_tys[0];
                if lty == "OoSList" {
                    code.push_str(&format!(
                        "  OoStr {} = oo_slist_get({}, {});\n",
                        t, cargs[0], cargs[1]
                    ));
                    Ok((code, t, "OoStr".into()))
                } else {
                    code.push_str(&format!(
                        "  long long {} = oo_ilist_get({}, {});\n",
                        t, cargs[0], cargs[1]
                    ));
                    Ok((code, t, "long long".into()))
                }
            }
            "list_len" => {
                let lty = &arg_tys[0];
                if lty == "OoSList" {
                    code.push_str(&format!(
                        "  long long {} = oo_slist_len({});\n",
                        t, cargs[0]
                    ));
                } else {
                    code.push_str(&format!(
                        "  long long {} = oo_ilist_len({});\n",
                        t, cargs[0]
                    ));
                }
                Ok((code, t, "long long".into()))
            }
            "chars_len" => {
                code.push_str(&format!(
                    "  long long {} = oo_chars_len({});\n",
                    t, cargs[0]
                ));
                Ok((code, t, "long long".into()))
            }
            "char_at" => {
                code.push_str(&format!(
                    "  OoStr {} = oo_char_at({}, {});\n",
                    t, cargs[0], cargs[1]
                ));
                Ok((code, t, "OoStr".into()))
            }
            "str_slice" => {
                code.push_str(&format!(
                    "  OoStr {} = oo_str_slice({}, {}, {});\n",
                    t, cargs[0], cargs[1], cargs[2]
                ));
                Ok((code, t, "OoStr".into()))
            }
            "char_is_digit" => {
                code.push_str(&format!(
                    "  int {} = oo_char_is_digit({});\n",
                    t, cargs[0]
                ));
                Ok((code, t, "int".into()))
            }
            "char_is_alpha" => {
                code.push_str(&format!(
                    "  int {} = oo_char_is_alpha({});\n",
                    t, cargs[0]
                ));
                Ok((code, t, "int".into()))
            }
            "char_is_space" => {
                code.push_str(&format!(
                    "  int {} = oo_char_is_space({});\n",
                    t, cargs[0]
                ));
                Ok((code, t, "int".into()))
            }
            "read_file" | "fs_read" => {
                let path = cargs.last().unwrap();
                code.push_str(&format!("  OoResS {} = oo_read_file({});\n", t, path));
                Ok((code, t, "OoResS".into()))
            }
            "write_file" | "fs_write" => {
                // path, content — last two stringish
                let path = if cargs.len() >= 2 {
                    &cargs[cargs.len() - 2]
                } else {
                    &cargs[0]
                };
                let content = cargs.last().unwrap();
                code.push_str(&format!(
                    "  OoResV {} = oo_write_file({}, {});\n",
                    t, path, content
                ));
                // map to OoResS-like for is_ok: use ok field
                Ok((code, t, "OoResV".into()))
            }
            "println" => {
                // handled at stmt level usually
                for (i, a) in cargs.iter().enumerate() {
                    let ty = &arg_tys[i];
                    if ty == "OoStr" {
                        code.push_str(&format!("  oo_print_str({});\n", a));
                    } else if ty == "int" {
                        code.push_str(&format!("  oo_print_bool({});\n", a));
                    } else {
                        code.push_str(&format!("  oo_print_int({});\n", a));
                    }
                }
                code.push_str("  oo_println();\n");
                Ok((code, "0".into(), "int".into()))
            }
            other if other.starts_with('.') => {
                bail!("C backend: unsupported method {}", other)
            }
            other => {
                let rty = self
                    .fn_ret
                    .get(other)
                    .cloned()
                    .unwrap_or_else(|| "long long".into());
                if rty == "void" {
                    code.push_str(&format!(
                        "  oo_{}({});\n",
                        other,
                        cargs.join(", ")
                    ));
                    Ok((code, "0".into(), "int".into()))
                } else {
                    code.push_str(&format!(
                        "  {} {} = oo_{}({});\n",
                        rty,
                        t,
                        other,
                        cargs.join(", ")
                    ));
                    Ok((code, t, rty))
                }
            }
        }
    }
}

pub fn runtime_c_path() -> PathBuf {
    // Prefer adjacent runtime from crate root
    let candidates = [
        PathBuf::from("runtime/chs_rt.c"),
        PathBuf::from("/home/jeryd/openooda/runtime/chs_rt.c"),
    ];
    for c in candidates {
        if c.exists() {
            return c;
        }
    }
    PathBuf::from("runtime/chs_rt.c")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn parse(src: &str) -> Program {
        let mut l = Lexer::new(src);
        let t = l.tokenize().unwrap();
        Parser::new(t).parse_program().unwrap()
    }

    #[test]
    fn emits_c_for_int_main() {
        let p = parse("pub fn main() { println(42); }\n");
        let c = CCodeGen::emit_c(&p).expect("emit");
        assert!(c.contains("int main"), "{}", c);
        assert!(c.contains("oo_print_int"), "{}", c);
    }

    #[test]
    fn emits_c_for_list_and_string() {
        let p = parse(
            r#"
            pub fn main() {
                let mut xs = list_new();
                xs = list_push(xs, 10);
                println(list_len(xs));
                println(chars_len("ab"));
            }
            "#,
        );
        let c = CCodeGen::emit_c(&p).expect("emit");
        assert!(c.contains("oo_ilist_new"), "{}", c);
        assert!(c.contains("oo_chars_len"), "{}", c);
    }
}
