// ===================================================================
// openOODA WebAssembly (.wat) Code Generator
//
// Honest subset: Int / Bool / Float arithmetic, function calls, `let`,
// `if`/`while`, interned String *literals* (data segments + `println_str`),
// and content `==`/`!=` via host import `env.streq` (NUL-terminated).
//
// Fail-closed (non-zero): Match, capability I/O, List/struct, string
// methods, string concatenation / arithmetic (no silent pointer math).
//
// String model: each distinct UTF-8 literal is interned once into linear
// memory as a NUL-terminated byte sequence; values are i32 offsets.
// Identical literals share one offset (W↓). Equality uses `$streq` so
// distinct intern slots with equal content also compare equal (host-defined).
//
// The emitted WAT is round-trip validated via `wasm-tools validate`
// when available, otherwise checked structurally for undeclared locals
// and missing `return` instructions.
// ===================================================================
use crate::ast::*;
use anyhow::{anyhow, bail, Result};
use std::collections::{BTreeMap, HashSet};
use std::process::Command;

thread_local! {
    /// Nested while break/continue label pairs for the current WASM emit.
    static WASM_LOOP_STACK: std::cell::RefCell<Vec<(String, String)>> =
        std::cell::RefCell::new(Vec::new());
    /// Intern pool for string literals in the current emit (order = data layout).
    static WASM_STRINGS: std::cell::RefCell<Vec<String>> =
        std::cell::RefCell::new(Vec::new());
}

/// Intern `s` into the WASM string pool; return its i32 data-segment offset.
/// Duplicate content reuses the first offset (zero-cost after first insert).
fn intern_string(s: &str) -> u32 {
    WASM_STRINGS.with(|cell| {
        let mut strings = cell.borrow_mut();
        let mut offset: u32 = 0;
        for existing in strings.iter() {
            if existing == s {
                return offset;
            }
            offset = offset.saturating_add(existing.len() as u32).saturating_add(1);
        }
        strings.push(s.to_string());
        offset
    })
}

pub struct WasmCodeGen;

impl WasmCodeGen {
    pub fn emit_wat(program: &Program) -> Result<String> {
        WASM_STRINGS.with(|s| s.borrow_mut().clear());
        let mut wat = String::new();
        wat.push_str(";; ===================================================================\n");
        wat.push_str(";; openOODA WebAssembly Text Format (.wat) Target Backend\n");
        wat.push_str(";; Generated by `ooda build --target wasm` (v0.24.0-alpha)\n");
        wat.push_str(";; ===================================================================\n\n");
        wat.push_str("(module\n");
        wat.push_str("  (import \"env\" \"println\" (func $println (param i64)))\n");
        wat.push_str("  (import \"env\" \"println_str\" (func $println_str (param i32)))\n");
        wat.push_str("  (import \"env\" \"streq\" (func $streq (param i32 i32) (result i32)))\n\n");

        let aliases = program.collect_type_aliases();
        for item in &program.items {
            if let Item::Function(func) = item {
                let f_wat = Self::emit_function(func, &aliases)?;
                wat.push_str(&f_wat);
                wat.push('\n');
            }
        }

        WASM_STRINGS.with(|strings| {
            let strings = strings.borrow();
            if !strings.is_empty() {
                wat.push_str("  (memory 1)\n");
                wat.push_str("  (export \"memory\" (memory 0))\n");
                let mut offset = 0;
                for s in strings.iter() {
                    let mut hex_str = String::new();
                    for b in s.as_bytes() {
                        hex_str.push_str(&format!("\\{:02x}", b));
                    }
                    hex_str.push_str("\\00"); // null terminator
                    wat.push_str(&format!("  (data (i32.const {}) \"{}\")\n", offset, hex_str));
                    offset += s.len() + 1;
                }
            }
        });

        wat.push_str(")\n");
        Self::validate_wat(&wat)?;
        Ok(wat)
    }

    fn emit_function(func: &FunctionDecl, aliases: &std::collections::HashMap<String, Type>) -> Result<String> {
        let mut f_wat = String::new();
        let is_main = func.name == "main";

        // Reject capability parameters — the WASM subset has no IO model.
        for p in &func.params {
            let resolved = p.param_type.resolve_alias(aliases);
            match resolved {
                Type::NetCap | Type::FsCap | Type::SysCap | Type::EnvCap => {
                    bail!(
                        "WASM backend does not support capability parameters in '{}' (parameter '{}'). \
                         Use `ooda run` for programs that exercise capability IO.",
                        func.name,
                        p.name
                    );
                }
                Type::String => {}
                Type::Option(_) | Type::Result(_, _) => bail!(
                    "WASM backend does not yet support Option/Result in '{}'. Use `ooda run`.",
                    func.name
                ),
                Type::List(_) => bail!(
                    "WASM backend does not yet support List in '{}'. Use `ooda run`.",
                    func.name
                ),
                Type::Struct { .. } => bail!(
                    "WASM backend does not yet support struct in '{}'. Use `ooda run`.",
                    func.name
                ),
                Type::Float | Type::Int | Type::Bool | Type::Void => {}
                Type::Custom(_) => {}
            }
        }
        // String returns are allowed (i32 data offset — not a full string object).

        // Helper: OODA `Type` → wasm primitive type name.
        let wat_param_ty = |t: &Type| -> Result<&'static str> {
            let resolved = t.resolve_alias(aliases);
            Ok(match resolved {
                Type::Int | Type::Bool => "i64",
                Type::String => "i32",
                Type::Float => "f64",
                Type::Void => "i64",
                _ => bail!("unsupported param type in WASM: {:?}", t),
            })
        };

        // Header
        f_wat.push_str(&format!("  (func ${}", func.name));
        if is_main {
            f_wat.push_str(" (export \"main\")");
        }
        for param in &func.params {
            let ty = wat_param_ty(&param.param_type)?;
            f_wat.push_str(&format!(" (param ${} {})", param.name, ty));
        }
        // The function's return type. `main` is special: the wasm
        // host entry-point returns i32, so we wrap i64 → i32 at the
        // end (and let f64 fall through unchanged).
        let ret_ty: &'static str = match &func.return_type {
            Type::Int | Type::Bool => "i64",
            Type::String => "i32",
            Type::Float => "f64",
            Type::Void => "i64",
            _ => "i64",
        };
        if is_main {
            f_wat.push_str(" (result i32)\n");
        } else {
            f_wat.push_str(&format!(" (result {})\n", ret_ty));
        }

        // Collect declared locals (from `let` bindings) with their
        // inferred wasm type. We infer the type from the literal
        // shape of the initializer; for non-literal initializers we
        // fall back to i64.
        let mut locals: BTreeMap<String, &'static str> = BTreeMap::new();
        // Params are also addressable as locals via the same names.
        for p in &func.params {
            locals.insert(p.name.clone(), wat_param_ty(&p.param_type)?);
        }
        for stmt in &func.body.stmts {
            if let Statement::Let { name, init, .. } = stmt {
                locals.insert(name.clone(), Self::infer_expr_type(init, &locals));
            }
        }
        for (name, ty) in &locals {
            f_wat.push_str(&format!("    (local ${} {})\n", name, ty));
        }

        // Walk statements, emitting body
        let mut emitted_return = false;
        for stmt in &func.body.stmts {
            match stmt {
                Statement::Let { name, init, .. } => {
                    let e_wat = Self::emit_expr(init, &locals)?;
                    f_wat.push_str(&e_wat);
                    f_wat.push_str(&format!("    local.set ${}\n", name));
                }
                Statement::FieldAssign { .. } => {
                    bail!("WASM backend does not support field assignment. Use `ooda run`.");
                }
                Statement::Assign { name, value, .. } => {
                    if !locals.contains_key(name) {
                        // Allow assign to params (also addressable as locals in WASM)
                    }
                    let e_wat = Self::emit_expr(value, &locals)?;
                    f_wat.push_str(&e_wat);
                    f_wat.push_str(&format!("    local.set ${}\n", name));
                }
                Statement::Return(Some(expr), _) => {
                    let e_wat = Self::emit_expr(expr, &locals)?;
                    f_wat.push_str(&e_wat);
                    if is_main {
                        f_wat.push_str("    i32.wrap_i64\n");
                    }
                    f_wat.push_str("    return\n");
                    emitted_return = true;
                }
                Statement::Return(None, _) => {
                    if is_main {
                        f_wat.push_str("    i32.const 0\n");
                        f_wat.push_str("    return\n");
                    } else {
                        f_wat.push_str("    return\n");
                    }
                    emitted_return = true;
                }
                other => {
                    // Let / assign / expr / while / break / continue
                    f_wat.push_str(&Self::emit_stmt_wat(other, &locals)?);
                }
            }
        }

        // Tail expression (if any)
        if let Some(body_expr) = &func.body.expr {
            let e_wat = Self::emit_expr(body_expr, &locals)?;
            f_wat.push_str(&e_wat);
            if is_main {
                f_wat.push_str("    i32.wrap_i64\n");
            }
            f_wat.push_str("    return\n");
            emitted_return = true;
        }

        if !emitted_return {
            if is_main {
                f_wat.push_str("    i32.const 0\n    return\n");
            } else {
                f_wat.push_str("    return\n");
            }
        }

        f_wat.push_str("  )\n");
        Ok(f_wat)
    }

    /// Emit WAT for an expression.
    ///
    /// Returns the WAT fragment that leaves the expression's value on
    /// the wasm stack. The caller does NOT need to know the result
    /// type — the existing WASM ops are polymorphic over i64 / f64
    /// in the relevant slots (e.g. `local.set` accepts both). Where
    /// the type DOES matter (Binary ops, Call to typed params), the
    /// fragment internally handles promotion via `f64.convert_i64_s`.
    fn emit_expr(expr: &Expression, locals: &BTreeMap<String, &'static str>) -> Result<String> {
        let mut wat = String::new();
        match expr {
            Expression::Literal(Literal::Int(n), _) => {
                wat.push_str(&format!("    i64.const {}\n", n));
            }
            Expression::Literal(Literal::Bool(b), _) => {
                wat.push_str(&format!("    i64.const {}\n", if *b { 1 } else { 0 }));
            }
            Expression::Literal(Literal::String(s), _) => {
                let offset = intern_string(s);
                wat.push_str(&format!("    i32.const {}\n", offset));
            }
            Expression::Literal(Literal::Float(f), _) => {
                wat.push_str(&format!("    f64.const {}\n", f));
            }
            Expression::Literal(Literal::Void, _) => {
                wat.push_str("    i64.const 0\n");
            }
            Expression::Variable(name, _) => {
                // local.get is type-polymorphic — works for both i64 and f64.
                wat.push_str(&format!("    local.get ${}\n", name));
            }
            Expression::Binary { op, left, right, .. } => {
                // Infer operand types. Prefer the declared type of a
                // local; fall back to the literal shape for fresh
                // expressions.
                let lhs_ty = Self::infer_expr_type(left, locals);
                let rhs_ty = Self::infer_expr_type(right, locals);
                let either_str = lhs_ty == "i32" || rhs_ty == "i32";
                // String pointers are not numbers: refuse arithmetic / ordering.
                // Eq/Neq allowed as *pointer identity* after literal interning.
                if either_str {
                    match op {
                        BinOp::Eq | BinOp::Neq => {}
                        BinOp::Add | BinOp::Sub | BinOp::Mul | BinOp::Div => {
                            bail!(
                                "WASM backend does not lower string arithmetic (`{:?}`); \
                                 use `ooda run` for concat / numeric conversion (no silent pointer math).",
                                op
                            );
                        }
                        BinOp::Gt | BinOp::Lt | BinOp::Gte | BinOp::Lte => {
                            bail!(
                                "WASM backend does not lower ordered compare on String pointers; use `ooda run`."
                            );
                        }
                        BinOp::And | BinOp::Or => {
                            bail!("WASM backend does not lower &&/|| on String; use `ooda run`.");
                        }
                        BinOp::DotDot | BinOp::DotDotEq => {
                            bail!("WASM backend does not yet lower range operators (`..`, `..=`). Use `ooda run`.")
                        }
                    }
                    if lhs_ty != "i32" || rhs_ty != "i32" {
                        bail!(
                            "WASM backend does not mix String pointers with numeric types in binary ops; use `ooda run`."
                        );
                    }
                }
                // Promote i64 → f64 if either operand is f64.
                let promote = |ty: &'static str, code: &mut String| {
                    if ty == "i64" && (lhs_ty == "f64" || rhs_ty == "f64") {
                        code.push_str("    f64.convert_i64_s\n");
                    }
                };
                let l_wat = Self::emit_expr(left, locals)?;
                let mut l_code = String::new();
                promote(lhs_ty, &mut l_code);
                wat.push_str(&l_wat);
                wat.push_str(&l_code);

                let r_wat = Self::emit_expr(right, locals)?;
                let mut r_code = String::new();
                promote(rhs_ty, &mut r_code);
                wat.push_str(&r_wat);
                wat.push_str(&r_code);

                // Both operands are now on the stack as the same type.
                let ty = if lhs_ty == "f64" || rhs_ty == "f64" {
                    "f64"
                } else if either_str {
                    "i32"
                } else {
                    "i64"
                };
                match op {
                    BinOp::Add => wat.push_str(&format!("    {}.add\n", ty)),
                    BinOp::Sub => wat.push_str(&format!("    {}.sub\n", ty)),
                    BinOp::Mul => wat.push_str(&format!("    {}.mul\n", ty)),
                    BinOp::Div if ty == "i64" => wat.push_str("    i64.div_s\n"),
                    BinOp::Div => wat.push_str("    f64.div\n"),
                    // Comparisons yield i32 in WebAssembly; extend to i64 Bool model.
                    BinOp::Eq => {
                        if ty == "i32" {
                            wat.push_str("    call $streq\n");
                        } else {
                            wat.push_str(&format!("    {}.eq\n", ty));
                        }
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    BinOp::Neq => {
                        if ty == "i32" {
                            wat.push_str("    call $streq\n");
                            wat.push_str("    i32.eqz\n");
                        } else {
                            wat.push_str(&format!("    {}.ne\n", ty));
                        }
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    BinOp::Gt => {
                        if ty == "i64" {
                            wat.push_str("    i64.gt_s\n")
                        } else {
                            wat.push_str("    f64.gt\n")
                        }
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    BinOp::Lt => {
                        if ty == "i64" {
                            wat.push_str("    i64.lt_s\n")
                        } else {
                            wat.push_str("    f64.lt\n")
                        }
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    BinOp::Gte => {
                        if ty == "i64" {
                            wat.push_str("    i64.ge_s\n")
                        } else {
                            wat.push_str("    f64.ge\n")
                        }
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    BinOp::Lte => {
                        if ty == "i64" {
                            wat.push_str("    i64.le_s\n")
                        } else {
                            wat.push_str("    f64.le\n")
                        }
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    // Boolean ops stay i64.
                    BinOp::And | BinOp::Or if ty == "i64" => match op {
                        BinOp::And => wat.push_str("    i64.and\n"),
                        BinOp::Or => wat.push_str("    i64.or\n"),
                        _ => unreachable!(),
                    },
                    BinOp::And | BinOp::Or => bail!(
                        "WASM backend does not yet lower {} on Float operands in this alpha.",
                        match op {
                            BinOp::And => "&&",
                            BinOp::Or => "||",
                            _ => "?"
                        }
                    ),
                    BinOp::DotDot | BinOp::DotDotEq => {
                        bail!("WASM backend does not yet lower range operators (`..`, `..=`). Use `ooda run`.")
                    }
                }
            }
            Expression::Call { name, args, .. } => {
                if name.starts_with('.') {
                    bail!(
                        "WASM backend does not yet support method-style calls (`{}`). Use `ooda run`.",
                        name
                    );
                }
                if name == "println" {
                    if args.is_empty() {
                        bail!("WASM println requires at least one Int or String argument");
                    }
                    for arg in args {
                        // Int → $println (i64); String (i32 offset) → $println_str; Float truncates.
                        let arg_ty = Self::infer_expr_type(arg, locals);
                        wat.push_str(&Self::emit_expr(arg, locals)?);
                        if arg_ty == "f64" {
                            wat.push_str("    i64.trunc_f64_s\n");
                            wat.push_str("    call $println\n");
                        } else if arg_ty == "i32" {
                            wat.push_str("    call $println_str\n");
                        } else {
                            wat.push_str("    call $println\n");
                        }
                    }
                } else {
                    for arg in args {
                        wat.push_str(&Self::emit_expr(arg, locals)?);
                    }
                    wat.push_str(&format!("    call ${}\n", name));
                }
            }
            Expression::If {
                cond,
                then_branch,
                else_branch,
                ..
            } => {
                wat.push_str(&Self::emit_if(cond, then_branch, else_branch.as_ref(), locals)?);
            }
            Expression::Unary { op, expr, .. } => {
                let inner_ty = Self::infer_expr_type(expr, locals);
                wat.push_str(&Self::emit_expr(expr, locals)?);
                match op {
                    UnaryOp::Not => {
                        // `!` on Int → eqz. On Float → compare ≠ 0.0 via f64.const 0.0; f64.ne.
                        match inner_ty {
                            "i64" => wat.push_str("    i64.eqz\n"),
                            "f64" => {
                                wat.push_str("    f64.const 0.0\n");
                                wat.push_str("    f64.ne\n");
                            }
                            _ => wat.push_str("    i64.eqz\n"),
                        }
                    }
                    UnaryOp::Neg => match inner_ty {
                        "i64" => {
                            wat.push_str("    i64.const -1\n");
                            wat.push_str("    i64.mul\n");
                        }
                        "f64" => {
                            wat.push_str("    f64.const -1.0\n");
                            wat.push_str("    f64.mul\n");
                        }
                        _ => {
                            wat.push_str("    i64.const -1\n");
                            wat.push_str("    i64.mul\n");
                        }
                    },
                }
            }
            Expression::While { cond, body, .. } => {
                wat.push_str(&Self::emit_while(cond, body, locals)?);
            }
            Expression::Match { .. } => {
                bail!("WASM backend does not yet lower `match` expressions; use `ooda run`.")
            }
            Expression::StructLit { .. } => {
                bail!("WASM backend does not yet lower struct literals; use `ooda run`.")
            }
        }
        Ok(wat)
    }

    /// Best-effort type inference for an expression: declared local
    /// type > literal shape > default i64.
    fn infer_expr_type(expr: &Expression, locals: &BTreeMap<String, &'static str>) -> &'static str {
        match expr {
            Expression::Literal(Literal::Float(_), _) => "f64",
            Expression::Literal(Literal::Bool(_), _) => "i64",
            Expression::Literal(Literal::Int(_), _) => "i64",
            Expression::Literal(Literal::String(_), _) => "i32",
            Expression::Variable(name, _) => locals.get(name).copied().unwrap_or("i64"),
            Expression::Binary { op, left, right, .. } => {
                // Comparisons always yield Bool (i64 0/1). Arithmetic preserves operand class.
                match op {
                    BinOp::Eq
                    | BinOp::Neq
                    | BinOp::Gt
                    | BinOp::Lt
                    | BinOp::Gte
                    | BinOp::Lte
                    | BinOp::And
                    | BinOp::Or => "i64",
                    _ => {
                        let lt = Self::infer_expr_type(left, locals);
                        let rt = Self::infer_expr_type(right, locals);
                        if lt == "f64" || rt == "f64" {
                            "f64"
                        } else if lt == "i32" || rt == "i32" {
                            "i32"
                        } else {
                            "i64"
                        }
                    }
                }
            }
            // Default to i64 for everything else (calls, if, etc.).
            _ => "i64",
        }
    }

    fn emit_while(
        cond: &Expression,
        body: &Block,
        locals: &BTreeMap<String, &'static str>,
    ) -> Result<String> {
        let mut wat = String::new();
        let cond_ty = Self::infer_expr_type(cond, locals);
        static LOOP_ID: std::sync::atomic::AtomicU32 = std::sync::atomic::AtomicU32::new(0);
        let id = LOOP_ID.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let br_lab = format!("break_{}", id);
        let cont_lab = format!("continue_{}", id);
        WASM_LOOP_STACK.with(|s| s.borrow_mut().push((br_lab.clone(), cont_lab.clone())));
        // while cond { body } → break when cond is *false* (zero).
        wat.push_str(&format!("    block ${}\n", br_lab));
        wat.push_str(&format!("      loop ${}\n", cont_lab));
        wat.push_str(&Self::emit_expr(cond, locals)?);
        match cond_ty {
            "f64" => {
                wat.push_str("        f64.const 0.0\n");
                wat.push_str("        f64.eq\n"); // 1 when false → break
            }
            _ => {
                wat.push_str("        i64.eqz\n");
            }
        }
        wat.push_str(&format!("        br_if ${}\n", br_lab));
        for stmt in &body.stmts {
            wat.push_str(&Self::emit_stmt_wat(stmt, locals)?);
        }
        wat.push_str(&format!("        br ${}\n", cont_lab));
        wat.push_str("      end\n");
        wat.push_str("    end\n");
        WASM_LOOP_STACK.with(|s| { s.borrow_mut().pop(); });
        wat.push_str("    i32.const 0\n");
        wat.push_str("    drop\n");
        Ok(wat)
    }

/// Lower `if cond { then } else { els }` to WAT.
    ///
    /// The condition is normalised to i32 (0 = false, non-zero = true).
    /// Both branches must produce a single value of the unified
    /// type (i64 or f64) on the stack so the outer block has a
    /// uniform `(result T)` signature.
    fn emit_if(
        cond: &Expression,
        then_branch: &Block,
        else_branch: Option<&Block>,
        locals: &BTreeMap<String, &'static str>,
    ) -> Result<String> {
        // Reject `match` (not yet lowered) anywhere in the branches.
        for stmt in &then_branch.stmts {
            if matches!(stmt, Statement::Expr(expr, _) | Statement::Return(Some(expr), _)
                if matches!(expr, Expression::Match { .. }))
            {
                bail!("WASM backend does not yet lower `match` expressions; use `ooda run`.");
            }
        }
        if let Some(eb) = else_branch {
            for stmt in &eb.stmts {
                if matches!(stmt, Statement::Expr(expr, _) | Statement::Return(Some(expr), _)
                    if matches!(expr, Expression::Match { .. }))
                {
                    bail!("WASM backend does not yet lower `match` expressions; use `ooda run`.");
                }
            }
        }

        // Determine the unified result type of the if from the
        // tail expression of each branch (or default to i64).
        let branch_ty = |b: &Block| -> &'static str {
            if let Some(tail) = &b.expr {
                Self::expr_literal_type(tail, locals)
            } else {
                // Walk statements; pick the last Return's type, else Void.
                let mut ty = "i64";
                for s in &b.stmts {
                    if let Statement::Return(Some(e), _) = s {
                        ty = Self::expr_literal_type(e, locals);
                    }
                }
                ty
            }
        };
        let result_ty = if let Some(eb) = else_branch {
            let t_ty = branch_ty(then_branch);
            let e_ty = branch_ty(eb);
            if t_ty == "f64" || e_ty == "f64" { "f64" } else { "i64" }
        } else {
            branch_ty(then_branch)
        };

        let mut wat = String::new();

        // 1. Condition, normalised to i32
        wat.push_str(&Self::emit_expr(cond, locals)?);
        wat.push_str(&format!(
            "    {}.const 0\n    {}.ne\n",
            if Self::infer_expr_type(cond, locals) == "f64" { "f64" } else { "i64" },
            if Self::infer_expr_type(cond, locals) == "f64" { "f64" } else { "i64" },
        ));

        // 2. Structured if/then/else with the unified result type.
        // Each arm must leave exactly one `result_ty` value — side-effect-only
        // arms (e.g. println) push a zero of that type so wasmtime type-checks.
        wat.push_str(&format!("    (if (result {})\n", result_ty));
        wat.push_str("      (then\n");
        wat.push_str(&Self::emit_if_branch(then_branch, locals, result_ty)?);
        wat.push_str("      )\n");
        wat.push_str("      (else\n");
        if let Some(eb) = else_branch {
            wat.push_str(&Self::emit_if_branch(eb, locals, result_ty)?);
        } else {
            wat.push_str(&format!("        {}.const 0\n", result_ty));
        }
        wat.push_str("      )\n");
        wat.push_str("    )\n");

        Ok(wat)
    }

    /// Emit one if-arm: statements + optional tail expr, else default zero.
    fn emit_if_branch(
        branch: &Block,
        locals: &BTreeMap<String, &'static str>,
        result_ty: &'static str,
    ) -> Result<String> {
        let mut wat = String::new();
        for stmt in &branch.stmts {
            wat.push_str(&Self::emit_stmt_wat(stmt, locals)?);
        }
        if let Some(tail) = &branch.expr {
            wat.push_str(&Self::emit_expr(tail, locals)?);
        } else {
            // No value-producing tail: synthesize unit for `(result T)`.
            wat.push_str(&format!("        {}.const 0\n", result_ty));
        }
        Ok(wat)
    }

    /// Type of a literal-shaped expression (ignores locals/operations).
    fn expr_literal_type(expr: &Expression, locals: &BTreeMap<String, &'static str>) -> &'static str {
        Self::infer_expr_type(expr, locals)
    }

    /// Emit WAT for one statement (used by `emit_if` for each
    /// branch). Mirrors the body-emission logic in `emit_function`.
    fn emit_stmt_wat(stmt: &Statement, locals: &BTreeMap<String, &'static str>) -> Result<String> {
        let mut wat = String::new();
        match stmt {
            Statement::Let { name, init, .. } => {
                wat.push_str(&Self::emit_expr(init, locals)?);
                wat.push_str(&format!("        local.set ${}\n", name));
            }
                Statement::FieldAssign { .. } => {
                    bail!("WASM backend does not support field assignment. Use `ooda run`.");
                }
            Statement::Assign { name, value, .. } => {
                wat.push_str(&Self::emit_expr(value, locals)?);
                wat.push_str(&format!("        local.set ${}\n", name));
            }
            Statement::Return(Some(expr), _) => {
                wat.push_str(&Self::emit_expr(expr, locals)?);
                wat.push_str("        return\n");
            }
            Statement::Break(_) => {
                let br = WASM_LOOP_STACK.with(|s| {
                    s.borrow().last().map(|(b, _)| b.clone())
                }).ok_or_else(|| anyhow::anyhow!("WASM: break outside loop"))?;
                wat.push_str(&format!("        br ${}\n", br));
            }
            Statement::Continue(_) => {
                let cont = WASM_LOOP_STACK.with(|s| {
                    s.borrow().last().map(|(_, c)| c.clone())
                }).ok_or_else(|| anyhow::anyhow!("WASM: continue outside loop"))?;
                wat.push_str(&format!("        br ${}\n", cont));
            }
            Statement::Return(None, _) => {
                wat.push_str("        return\n");
            }
            Statement::Expr(expr, _) => {
                wat.push_str(&Self::emit_expr(expr, locals)?);
                // Statement-context: drop leftover stack values.
                // println consumes its args; if/while/other exprs leave a value.
                match expr {
                    Expression::Call { name, .. } if name == "println" => {}
                    _ => {
                        wat.push_str("        drop\n");
                    }
                }
            }
            Statement::While { cond, body, .. } => {
                wat.push_str(&Self::emit_while(cond, body, locals)?);
                // emit_while leaves an i32.const 0 — drop it in statement context.
                wat.push_str("        drop\n");
            }
        }
        Ok(wat)
    }

    /// Structural validation: scan the emitted WAT for undeclared locals and
    /// missing `return` instructions. Optionally round-trip with
    /// `wasm-tools validate` when available.
    fn validate_wat(wat: &str) -> Result<()> {
        if wat.is_empty() {
            bail!("WASM validation failed: empty WAT output");
        }
        // Track per-function locals.
        let mut current_locals: HashSet<String> = HashSet::new();
        let mut current_params: HashSet<String> = HashSet::new();
        let mut in_function = false;
        let mut saw_return = false;

        for line in wat.lines() {
            let t = line.trim();
            if t.starts_with("(func $") {
                if in_function && !saw_return {
                    bail!("WASM validation failed: previous function missing `return`");
                }
                in_function = true;
                saw_return = false;
                current_locals.clear();
                current_params.clear();
                // Parse `(func $name (param $p1 i64) ...`
                let after_func = t.trim_start_matches("(func $");
                if let Some(space_idx) = after_func.find(' ') {
                    let mut rest = &after_func[space_idx..];
                    // Consume export if present
                    if rest.trim_start().starts_with("(export") {
                        if let Some(close) = rest.find(')') {
                            rest = &rest[close + 1..];
                        }
                    }
                    while let Some(open) = rest.find("(param $") {
                        let after_param = &rest[open + "(param $".len()..];
                        if let Some(space_idx) = after_param.find(' ') {
                            let pname = &after_param[..space_idx];
                            current_params.insert(pname.to_string());
                            rest = &after_param[space_idx..];
                        } else {
                            break;
                        }
                    }
                }
            } else if t.starts_with("(local $") {
                let after_local = t.trim_start_matches("(local $");
                if let Some(space_idx) = after_local.find(' ') {
                    let lname = &after_local[..space_idx];
                    current_locals.insert(lname.to_string());
                }
            } else if t.starts_with("local.get $") || t.starts_with("local.set $") {
                let op = if t.starts_with("local.get") { "local.get" } else { "local.set" };
                let rest = &t[op.len() + 2..]; // skip "$" + name
                let name = rest.split_whitespace().next().unwrap_or("");
                if !current_params.contains(name) && !current_locals.contains(name) {
                    bail!(
                        "WASM validation failed: {} references undeclared local/param `${}` (must be in (param ...) or (local ...))",
                        op,
                        name
                    );
                }
            } else if t == "return" {
                saw_return = true;
            }
        }
        if in_function && !saw_return {
            bail!("WASM validation failed: last function missing `return`");
        }

        // Optional external validation
        if let Ok(status) = Self::run_wasm_tools_validate(wat) {
            if !status {
                bail!("WASM validation failed: `wasm-tools validate` rejected the WAT");
            }
        }
        Ok(())
    }

    fn run_wasm_tools_validate(wat: &str) -> Result<bool> {
        let candidates = ["wasm-tools", "wasm-tools-1", "wasm-tools-2"];
        let bin = candidates
            .into_iter()
            .find(|c| Command::new(c).arg("--version").output().is_ok());
        let Some(bin) = bin else {
            return Err(anyhow!("wasm-tools not installed"));
        };

        let dir = std::env::temp_dir().join(format!("ooda-wasm-{}", std::process::id()));
        std::fs::create_dir_all(&dir)?;
        let wat_path = dir.join("check.wat");
        std::fs::write(&wat_path, wat)?;
        let out = Command::new(bin)
            .arg("validate")
            .arg(&wat_path)
            .output()?;
        let _ = std::fs::remove_dir_all(&dir);
        Ok(out.status.success())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn parse(src: &str) -> Program {
        let mut l = Lexer::new(src);
        let tokens = l.tokenize().expect("lex");
        let mut p = Parser::new(tokens);
        p.parse_program().expect("parse")
    }

    #[test]
    fn emits_valid_wat_for_straight_line_int() {
        let prog = parse(
            r#"
            pub fn add(a: Int, b: Int) -> Int { return a + b; }
            pub fn main() { let x = add(2, 3); }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        assert!(wat.contains("(local $x i64)"), "wat:\n{}", wat);
        assert!(wat.contains("local.set $x"), "wat:\n{}", wat);
        assert!(wat.contains("i64.const 2"), "wat:\n{}", wat);
        assert!(wat.contains("i64.const 3"), "wat:\n{}", wat);
        assert!(wat.contains("call $add"), "wat:\n{}", wat);
    }

    #[test]
    fn accepts_string_literals_with_data_segment() {
        let prog = parse(r#"pub fn main() { let s = "hi"; }"#);
        let res = WasmCodeGen::emit_wat(&prog).unwrap();
        assert!(res.contains("(memory 1)"));
        assert!(res.contains(r#"(data (i32.const 0) "\68\69\00")"#));
    }

    #[test]
    fn interns_duplicate_string_literals_one_data_segment() {
        let prog = parse(
            r#"
pub fn main() {
    let a = "hello";
    let b = "hello";
    if a == b { println(1); } else { println(0); }
}
"#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).unwrap();
        // One data segment for "hello", not two
        let data_count = wat.matches("(data (i32.const").count();
        assert_eq!(data_count, 1, "expected single interned data segment:\n{}", wat);
        assert!(wat.contains("i32.const 0"), "both should load offset 0:\n{}", wat);
        assert!(wat.contains("call $streq"), "string == uses streq host import:\n{}", wat);
    }

    #[test]
    fn println_string_literal_uses_println_str() {
        let prog = parse(r#"pub fn main() { println("hi"); }"#);
        let wat = WasmCodeGen::emit_wat(&prog).unwrap();
        assert!(wat.contains("call $println_str"), "wat:\n{}", wat);
        assert!(wat.contains(r#"(data (i32.const 0) "\68\69\00")"#), "wat:\n{}", wat);
    }

    #[test]
    fn refuses_string_concat_no_pointer_math() {
        let prog = parse(
            r#"
pub fn main() {
    let a = "a";
    let b = "b";
    let c = a + b;
    println(c);
}
"#,
        );
        let err = WasmCodeGen::emit_wat(&prog).unwrap_err();
        let msg = format!("{}", err);
        assert!(
            msg.contains("string arithmetic") || msg.contains("pointer"),
            "expected refuse string +, got: {}",
            msg
        );
    }

    #[test]
    fn lowers_if_then_else_to_valid_wat() {
        let prog = parse(
            r#"
            pub fn pick(x: Int) -> Int {
                if x > 0 { return x; } else { return 0 - x; }
            }
            pub fn main() {}
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        // Both branches must produce i64 and the if must be a
        // structured (if (result i64) (then …) (else …)) block.
        assert!(wat.contains("(if (result i64)"), "wat:\n{}", wat);
        assert!(wat.contains("(then"), "wat:\n{}", wat);
        assert!(wat.contains("(else"), "wat:\n{}", wat);
    }

    #[test]
    fn lowers_if_without_else_with_default_zero_branch() {
        let prog = parse(
            r#"
            pub fn sign(x: Int) -> Int {
                if x >= 0 { return x; }
                return 0 - x;
            }
            pub fn main() {}
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        assert!(wat.contains("(if (result i64)"), "wat:\n{}", wat);
        assert!(wat.contains("i64.const 0"), "wat:\n{}", wat);
    }

    #[test]
    fn rejects_match_expressions_non_zero() {
        let prog = parse(
            r#"
            pub fn classify(x: Int) -> Int {
                match x {
                    0 => 0,
                    _ => 1,
                }
            }
            pub fn main() {}
            "#,
        );
        let res = WasmCodeGen::emit_wat(&prog);
        assert!(res.is_err());
        assert!(format!("{}", res.unwrap_err()).contains("match"));
    }

    #[test]
    fn rejects_capability_parameters_non_zero() {
        let prog = parse(
            r#"
            pub fn fetch(net: &NetCap, url: String) -> String { return fetch(url); }
            pub fn main() {}
            "#,
        );
        let res = WasmCodeGen::emit_wat(&prog);
        assert!(res.is_err());
        assert!(format!("{}", res.unwrap_err()).contains("capability"));
    }

    #[test]
    fn emits_local_decl_for_let() {
        let prog = parse(
            r#"
            pub fn main() {
                let a = 1;
                let b = 2;
                let c = a + b;
            }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        assert!(wat.contains("(local $a i64)"));
        assert!(wat.contains("(local $b i64)"));
        assert!(wat.contains("(local $c i64)"));
    }

    #[test]
    fn emits_println_int() {
        let prog = parse(
            r#"
            pub fn main() {
                let x = 42;
                println(x);
            }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        assert!(wat.contains("call $println"), "wat:\n{}", wat);
        assert!(wat.contains("local.get $x"), "wat:\n{}", wat);
    }

    #[test]
    fn emits_wasm_for_float_arithmetic() {
        let prog = parse(
            r#"
            pub fn main() {
                let x = 1.5 + 2.5;
                let y = x * 2.0;
                println(y);
            }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        // Float locals are f64
        assert!(wat.contains("(local $x f64)"), "wat:\n{}", wat);
        assert!(wat.contains("(local $y f64)"), "wat:\n{}", wat);
        // Float constants and ops
        assert!(wat.contains("f64.const 1.5"), "wat:\n{}", wat);
        assert!(wat.contains("f64.const 2.5"), "wat:\n{}", wat);
        assert!(wat.contains("f64.add"), "wat:\n{}", wat);
        assert!(wat.contains("f64.mul"), "wat:\n{}", wat);
        // println is the i64 host import, so the Float value is truncated
        assert!(wat.contains("i64.trunc_f64_s"), "wat:\n{}", wat);
    }

    #[test]
    fn while_breaks_when_condition_is_false_not_true() {
        // Polarity: br_if $break must fire when cond is *false* (i64.eqz),
        // not when true (old bug inverted loops so bodies never ran).
        let prog = parse(
            r#"
            pub fn main() {
                let mut i = 0;
                while i < 3 {
                    i = i + 1;
                }
                println(i);
            }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit while");
        assert!(
            wat.contains("i64.eqz"),
            "while must break on false via i64.eqz:\n{}",
            wat
        );
        // Must not use the inverted "ne 0 → break on true" pattern.
        assert!(
            !wat.contains("i64.ne\n        br_if $break_"),
            "inverted while polarity must not appear:\n{}",
            wat
        );
        assert!(
            wat.contains("br_if $break_") || wat.contains("br_if $break"),
            "wat:\n{}",
            wat
        );
        assert!(
            wat.contains("br $continue_") || wat.contains("br $continue"),
            "wat:\n{}",
            wat
        );
        // Comparisons produce i32 in WASM; we extend to i64 Bool model.
        assert!(
            wat.contains("i64.extend_i32_u"),
            "compare result must extend i32→i64:\n{}",
            wat
        );
    }

    #[test]
    fn nested_while_break_uses_unique_labels() {
        // Locals must be declared at function top — declare j outside.
        let prog = parse(
            r#"
            pub fn main() -> Int {
                let mut i = 0;
                let mut j = 0;
                while i < 2 {
                    j = 0;
                    while j < 3 {
                        if j == 1 { break; }
                        j = j + 1;
                    }
                    i = i + 1;
                }
                return i;
            }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit nested while");
        assert!(
            wat.matches("block $break_").count() >= 2,
            "expected unique nested break labels, got:\n{}",
            wat
        );
        assert!(
            wat.contains("br $break_"),
            "inner break must target labeled break block:\n{}",
            wat
        );
    }

    #[test]
    fn rejects_match_expressions_in_wasm() {
        let prog = parse(
            r#"
            pub fn classify(x: Int) -> Int {
                match x {
                    0 => 0,
                    _ => 1,
                }
            }
            pub fn main() {}
            "#,
        );
        let res = WasmCodeGen::emit_wat(&prog);
        assert!(res.is_err());
        assert!(format!("{}", res.unwrap_err()).contains("match"));
    }
}
