// ===================================================================
// openOODA WebAssembly (.wat) Code Generator
//
// Honest subset: supports Int / Bool arithmetic, function calls, and
// `let` bindings with i64 values. Anything outside the subset (String
// literals, If/Match expressions, capability IO, Float, etc.) is
// rejected with a `bail!` so `ooda build --target wasm` fails
// non-zero instead of silently emitting structurally invalid WAT.
//
// The emitted WAT is round-trip validated via `wasm-tools validate`
// when available, otherwise checked structurally for undeclared locals
// and missing `return` instructions.
// ===================================================================
use crate::ast::*;
use anyhow::{anyhow, bail, Result};
use std::collections::{BTreeSet, HashSet};
use std::process::Command;

pub struct WasmCodeGen;

impl WasmCodeGen {
    pub fn emit_wat(program: &Program) -> Result<String> {
        let mut wat = String::new();
        wat.push_str(";; ===================================================================\n");
        wat.push_str(";; openOODA WebAssembly Text Format (.wat) Target Backend\n");
        wat.push_str(";; Generated by `ooda build --target wasm` (v0.12.0-alpha)\n");
        wat.push_str(";; ===================================================================\n\n");
        wat.push_str("(module\n");
        wat.push_str("  (import \"env\" \"println\" (func $println (param i64)))\n\n");

        for item in &program.items {
            if let Item::Function(func) = item {
                let f_wat = Self::emit_function(func)?;
                wat.push_str(&f_wat);
                wat.push('\n');
            }
        }

        wat.push_str(")\n");
        Self::validate_wat(&wat)?;
        Ok(wat)
    }

    fn emit_function(func: &FunctionDecl) -> Result<String> {
        let mut f_wat = String::new();
        let is_main = func.name == "main";

        // Reject capability parameters — the WASM subset has no IO model.
        for p in &func.params {
            match p.param_type {
                Type::NetCap | Type::FsCap | Type::SysCap | Type::EnvCap => {
                    bail!(
                        "WASM backend does not support capability parameters in '{}' (parameter '{}'). \
                         Use `ooda run` for programs that exercise capability IO.",
                        func.name,
                        p.name
                    );
                }
                Type::Float => bail!(
                    "WASM backend does not yet support Float in '{}'. Use `ooda run` or rewrite to Int.",
                    func.name
                ),
                Type::String => bail!(
                    "WASM backend does not yet support String in '{}'. Use `ooda run`.",
                    func.name
                ),
                Type::Option(_) | Type::Result(_, _) => bail!(
                    "WASM backend does not yet support Option/Result in '{}'. Use `ooda run`.",
                    func.name
                ),
                _ => {}
            }
        }
        if matches!(func.return_type, Type::Float | Type::String) {
            bail!(
                "WASM backend does not yet support return type {:?} in '{}'. Use `ooda run`.",
                func.return_type,
                func.name
            );
        }

        // Header
        f_wat.push_str(&format!("  (func ${}", func.name));
        if is_main {
            f_wat.push_str(" (export \"main\")");
        }
        for param in &func.params {
            f_wat.push_str(&format!(" (param ${} i64)", param.name));
        }
        if is_main {
            f_wat.push_str(" (result i32)\n");
        } else {
            f_wat.push_str(" (result i64)\n");
        }

        // Collect declared locals (from `let` bindings)
        let mut locals: BTreeSet<String> = BTreeSet::new();
        for stmt in &func.body.stmts {
            if let Statement::Let { name, .. } = stmt {
                locals.insert(name.clone());
            }
        }
        for name in &locals {
            f_wat.push_str(&format!("    (local ${} i64)\n", name));
        }

        // Walk statements, emitting body
        let mut emitted_return = false;
        for stmt in &func.body.stmts {
            match stmt {
                Statement::Let { name, init, .. } => {
                    let e_wat = Self::emit_expr(init, &locals)?;
                    f_wat.push_str(&e_wat);
                    f_wat.push_str(&format!("    local.set ${}\n", name));
                }
                Statement::Return(Some(expr), _) => {
                    let e_wat = Self::emit_expr(expr, &locals)?;
                    f_wat.push_str(&e_wat);
                    if is_main {
                        f_wat.push_str("    i32.wrap_i64\n");
                    }
                    f_wat.push_str("    return\n");
                    emitted_return = true;
                }
                Statement::Return(None, _) => {
                    if is_main {
                        f_wat.push_str("    i32.const 0\n");
                        f_wat.push_str("    return\n");
                    } else {
                        f_wat.push_str("    return\n");
                    }
                    emitted_return = true;
                }
                Statement::Expr(expr, _) => {
                    let e_wat = Self::emit_expr(expr, &locals)?;
                    f_wat.push_str(&e_wat);
                }
            }
        }

        // Tail expression (if any)
        if let Some(body_expr) = &func.body.expr {
            let e_wat = Self::emit_expr(body_expr, &locals)?;
            f_wat.push_str(&e_wat);
            if is_main {
                f_wat.push_str("    i32.wrap_i64\n");
            }
            f_wat.push_str("    return\n");
            emitted_return = true;
        }

        if !emitted_return {
            if is_main {
                f_wat.push_str("    i32.const 0\n    return\n");
            } else {
                f_wat.push_str("    return\n");
            }
        }

        f_wat.push_str("  )\n");
        Ok(f_wat)
    }

    fn emit_expr(expr: &Expression, locals: &BTreeSet<String>) -> Result<String> {
        let mut wat = String::new();
        match expr {
            Expression::Literal(Literal::Int(n), _) => {
                wat.push_str(&format!("    i64.const {}\n", n));
            }
            Expression::Literal(Literal::Bool(b), _) => {
                wat.push_str(&format!("    i64.const {}\n", if *b { 1 } else { 0 }));
            }
            Expression::Literal(Literal::String(_), _) => {
                bail!("WASM backend does not support string literals; use `ooda run`.");
            }
            Expression::Literal(Literal::Float(_), _) => {
                bail!("WASM backend does not support float literals; use `ooda run`.");
            }
            Expression::Literal(Literal::Void, _) => {
                wat.push_str("    i64.const 0\n");
            }
            Expression::Variable(name, _) => {
                if locals.contains(name) {
                    wat.push_str(&format!("    local.get ${}\n", name));
                } else {
                    // Defer to function parameter via $name
                    wat.push_str(&format!("    local.get ${}\n", name));
                }
            }
            Expression::Binary { op, left, right, .. } => {
                let l_wat = Self::emit_expr(left, locals)?;
                let r_wat = Self::emit_expr(right, locals)?;
                wat.push_str(&l_wat);
                wat.push_str(&r_wat);
                match op {
                    BinOp::Add => wat.push_str("    i64.add\n"),
                    BinOp::Sub => wat.push_str("    i64.sub\n"),
                    BinOp::Mul => wat.push_str("    i64.mul\n"),
                    BinOp::Div => wat.push_str("    i64.div_s\n"),
                    BinOp::Eq => wat.push_str("    i64.eq\n"),
                    BinOp::Neq => wat.push_str("    i64.ne\n"),
                    BinOp::Gt => wat.push_str("    i64.gt_s\n"),
                    BinOp::Lt => wat.push_str("    i64.lt_s\n"),
                    BinOp::Gte => wat.push_str("    i64.ge_s\n"),
                    BinOp::Lte => wat.push_str("    i64.le_s\n"),
                    BinOp::And => wat.push_str("    i64.and\n"),
                    BinOp::Or => wat.push_str("    i64.or\n"),
                    BinOp::DotDot | BinOp::DotDotEq => {
                        bail!("WASM backend does not yet lower range operators (`..`, `..=`). Use `ooda run`.")
                    }
                }
            }
            Expression::Call { name, args, .. } => {
                if name.starts_with('.') {
                    bail!(
                        "WASM backend does not yet support method-style calls (`{}`). Use `ooda run`.",
                        name
                    );
                }
                if name == "println" {
                    bail!(
                        "WASM backend cannot lower `println` directly (the imported host function expects i64, not String). \
                         Use `ooda run`."
                    );
                }
                for arg in args {
                    wat.push_str(&Self::emit_expr(arg, locals)?);
                }
                wat.push_str(&format!("    call ${}\n", name));
            }
            Expression::If { .. } => {
                bail!("WASM backend does not yet lower `if` expressions; use `ooda run` or `ooda build` (LLVM).")
            }
            Expression::Match { .. } => {
                bail!("WASM backend does not yet lower `match` expressions; use `ooda run`.")
            }
        }
        Ok(wat)
    }

    /// Structural validation: scan the emitted WAT for undeclared locals and
    /// missing `return` instructions. Optionally round-trip with
    /// `wasm-tools validate` if it's on PATH.
    fn validate_wat(wat: &str) -> Result<()> {
        if wat.is_empty() {
            bail!("WASM validation failed: empty WAT output");
        }
        // Track per-function locals.
        let mut current_locals: HashSet<String> = HashSet::new();
        let mut current_params: HashSet<String> = HashSet::new();
        let mut in_function = false;
        let mut saw_return = false;

        for line in wat.lines() {
            let t = line.trim();
            if t.starts_with("(func $") {
                if in_function && !saw_return {
                    bail!("WASM validation failed: previous function missing `return`");
                }
                in_function = true;
                saw_return = false;
                current_locals.clear();
                current_params.clear();
                // Parse `(func $name (param $p1 i64) ...`
                let after_func = t.trim_start_matches("(func $");
                if let Some(space_idx) = after_func.find(' ') {
                    let mut rest = &after_func[space_idx..];
                    // Consume export if present
                    if rest.trim_start().starts_with("(export") {
                        if let Some(close) = rest.find(')') {
                            rest = &rest[close + 1..];
                        }
                    }
                    while let Some(open) = rest.find("(param $") {
                        let after_param = &rest[open + "(param $".len()..];
                        if let Some(space_idx) = after_param.find(' ') {
                            let pname = &after_param[..space_idx];
                            current_params.insert(pname.to_string());
                            rest = &after_param[space_idx..];
                        } else {
                            break;
                        }
                    }
                }
            } else if t.starts_with("(local $") {
                let after_local = t.trim_start_matches("(local $");
                if let Some(space_idx) = after_local.find(' ') {
                    let lname = &after_local[..space_idx];
                    current_locals.insert(lname.to_string());
                }
            } else if t.starts_with("local.get $") || t.starts_with("local.set $") {
                let op = if t.starts_with("local.get") { "local.get" } else { "local.set" };
                let rest = &t[op.len() + 2..]; // skip "$" + name
                let name = rest.split_whitespace().next().unwrap_or("");
                if !current_params.contains(name) && !current_locals.contains(name) {
                    bail!(
                        "WASM validation failed: {} references undeclared local/param `${}` (must be in (param ...) or (local ...))",
                        op,
                        name
                    );
                }
            } else if t == "return" {
                saw_return = true;
            }
        }
        if in_function && !saw_return {
            bail!("WASM validation failed: last function missing `return`");
        }

        // Optional external validation
        if let Ok(status) = Self::run_wasm_tools_validate(wat) {
            if !status {
                bail!("WASM validation failed: `wasm-tools validate` rejected the WAT");
            }
        }
        Ok(())
    }

    fn run_wasm_tools_validate(wat: &str) -> Result<bool> {
        let candidates = ["wasm-tools", "wasm-tools-1", "wasm-tools-2"];
        let bin = candidates
            .into_iter()
            .find(|c| Command::new(c).arg("--version").output().is_ok());
        let Some(bin) = bin else {
            return Err(anyhow!("wasm-tools not installed"));
        };

        let dir = std::env::temp_dir().join(format!("ooda-wasm-{}", std::process::id()));
        std::fs::create_dir_all(&dir)?;
        let wat_path = dir.join("check.wat");
        std::fs::write(&wat_path, wat)?;
        let out = Command::new(bin)
            .arg("validate")
            .arg(&wat_path)
            .output()?;
        let _ = std::fs::remove_dir_all(&dir);
        Ok(out.status.success())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn parse(src: &str) -> Program {
        let mut l = Lexer::new(src);
        let tokens = l.tokenize().expect("lex");
        let mut p = Parser::new(tokens);
        p.parse_program().expect("parse")
    }

    #[test]
    fn emits_valid_wat_for_straight_line_int() {
        let prog = parse(
            r#"
            pub fn add(a: Int, b: Int) -> Int { return a + b; }
            pub fn main() { let x = add(2, 3); }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        assert!(wat.contains("(local $x i64)"), "wat:\n{}", wat);
        assert!(wat.contains("local.set $x"), "wat:\n{}", wat);
        assert!(wat.contains("i64.const 2"), "wat:\n{}", wat);
        assert!(wat.contains("i64.const 3"), "wat:\n{}", wat);
        assert!(wat.contains("call $add"), "wat:\n{}", wat);
    }

    #[test]
    fn rejects_string_literals_non_zero() {
        let prog = parse(r#"pub fn main() { let s = "hi"; }"#);
        let res = WasmCodeGen::emit_wat(&prog);
        assert!(res.is_err());
        assert!(format!("{}", res.unwrap_err()).contains("string literal"));
    }

    #[test]
    fn rejects_if_expressions_non_zero() {
        let prog = parse(
            r#"
            pub fn pick(x: Int) -> Int {
                if x > 0 { return x; } else { return 0 - x; }
            }
            pub fn main() {}
            "#,
        );
        let res = WasmCodeGen::emit_wat(&prog);
        assert!(res.is_err());
        assert!(format!("{}", res.unwrap_err()).contains("`if` expressions"));
    }

    #[test]
    fn rejects_capability_parameters_non_zero() {
        let prog = parse(
            r#"
            pub fn fetch(net: &NetCap, url: String) -> String { return fetch(url); }
            pub fn main() {}
            "#,
        );
        let res = WasmCodeGen::emit_wat(&prog);
        assert!(res.is_err());
        assert!(format!("{}", res.unwrap_err()).contains("capability"));
    }

    #[test]
    fn emits_local_decl_for_let() {
        let prog = parse(
            r#"
            pub fn main() {
                let a = 1;
                let b = 2;
                let c = a + b;
            }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        assert!(wat.contains("(local $a i64)"));
        assert!(wat.contains("(local $b i64)"));
        assert!(wat.contains("(local $c i64)"));
    }
}