// ===================================================================
// openOODA WebAssembly (.wat) Code Generator
//
// Honest subset: supports Int / Bool arithmetic, function calls,
// `let` bindings, and `if / then / else` expressions (both branches
// required; i64 result type). Anything outside the subset
// (String literals, Match expressions, capability IO, Float, etc.)
// is rejected with a `bail!` so `ooda build --target wasm` fails
// non-zero instead of silently emitting structurally invalid WAT.
//
// The emitted WAT is round-trip validated via `wasm-tools validate`
// when available, otherwise checked structurally for undeclared locals
// and missing `return` instructions.
// ===================================================================
use crate::ast::*;
use anyhow::{anyhow, bail, Result};
use std::collections::{BTreeMap, HashSet};
use std::process::Command;

pub struct WasmCodeGen;

impl WasmCodeGen {
    pub fn emit_wat(program: &Program) -> Result<String> {
        let mut wat = String::new();
        wat.push_str(";; ===================================================================\n");
        wat.push_str(";; openOODA WebAssembly Text Format (.wat) Target Backend\n");
        wat.push_str(";; Generated by `ooda build --target wasm` (v0.24.0-alpha)\n");
        wat.push_str(";; ===================================================================\n\n");
        wat.push_str("(module\n");
        wat.push_str("  (import \"env\" \"println\" (func $println (param i64)))\n\n");

        let aliases = program.collect_type_aliases();
        for item in &program.items {
            if let Item::Function(func) = item {
                let f_wat = Self::emit_function(func, &aliases)?;
                wat.push_str(&f_wat);
                wat.push('\n');
            }
        }

        wat.push_str(")\n");
        Self::validate_wat(&wat)?;
        Ok(wat)
    }

    fn emit_function(func: &FunctionDecl, aliases: &std::collections::HashMap<String, Type>) -> Result<String> {
        let mut f_wat = String::new();
        let is_main = func.name == "main";

        // Reject capability parameters — the WASM subset has no IO model.
        for p in &func.params {
            let resolved = p.param_type.resolve_alias(aliases);
            match resolved {
                Type::NetCap | Type::FsCap | Type::SysCap | Type::EnvCap => {
                    bail!(
                        "WASM backend does not support capability parameters in '{}' (parameter '{}'). \
                         Use `ooda run` for programs that exercise capability IO.",
                        func.name,
                        p.name
                    );
                }
                Type::String => bail!(
                    "WASM backend does not yet support String in '{}'. Use `ooda run`.",
                    func.name
                ),
                Type::Option(_) | Type::Result(_, _) => bail!(
                    "WASM backend does not yet support Option/Result in '{}'. Use `ooda run`.",
                    func.name
                ),
                Type::List(_) => bail!(
                    "WASM backend does not yet support List in '{}'. Use `ooda run`.",
                    func.name
                ),
                Type::Struct { .. } => bail!(
                    "WASM backend does not yet support struct in '{}'. Use `ooda run`.",
                    func.name
                ),
                Type::Float | Type::Int | Type::Bool | Type::Void => {}
                Type::Custom(_) => {}
            }
        }
        if matches!(func.return_type.resolve_alias(aliases), Type::String) {
            bail!(
                "WASM backend does not yet support String return in '{}'. Use `ooda run`.",
                func.name
            );
        }

        // Helper: OODA `Type` → wasm primitive type name.
        let wat_param_ty = |t: &Type| -> Result<&'static str> {
            let resolved = t.resolve_alias(aliases);
            Ok(match resolved {
                Type::Int | Type::Bool => "i64",
                Type::Float => "f64",
                Type::Void => "i64",
                _ => bail!("unsupported param type in WASM: {:?}", t),
            })
        };

        // Header
        f_wat.push_str(&format!("  (func ${}", func.name));
        if is_main {
            f_wat.push_str(" (export \"main\")");
        }
        for param in &func.params {
            let ty = wat_param_ty(&param.param_type)?;
            f_wat.push_str(&format!(" (param ${} {})", param.name, ty));
        }
        // The function's return type. `main` is special: the wasm
        // host entry-point returns i32, so we wrap i64 → i32 at the
        // end (and let f64 fall through unchanged).
        let ret_ty: &'static str = match &func.return_type {
            Type::Int | Type::Bool => "i64",
            Type::Float => "f64",
            Type::Void => "i64",
            _ => "i64",
        };
        if is_main {
            f_wat.push_str(" (result i32)\n");
        } else {
            f_wat.push_str(&format!(" (result {})\n", ret_ty));
        }

        // Collect declared locals (from `let` bindings) with their
        // inferred wasm type. We infer the type from the literal
        // shape of the initializer; for non-literal initializers we
        // fall back to i64.
        let mut locals: BTreeMap<String, &'static str> = BTreeMap::new();
        // Params are also addressable as locals via the same names.
        for p in &func.params {
            locals.insert(p.name.clone(), wat_param_ty(&p.param_type)?);
        }
        for stmt in &func.body.stmts {
            if let Statement::Let { name, init, .. } = stmt {
                locals.insert(name.clone(), Self::infer_expr_type(init, &locals));
            }
        }
        for (name, ty) in &locals {
            f_wat.push_str(&format!("    (local ${} {})\n", name, ty));
        }

        // Walk statements, emitting body
        let mut emitted_return = false;
        for stmt in &func.body.stmts {
            match stmt {
                Statement::Let { name, init, .. } => {
                    let e_wat = Self::emit_expr(init, &locals)?;
                    f_wat.push_str(&e_wat);
                    f_wat.push_str(&format!("    local.set ${}\n", name));
                }
                Statement::FieldAssign { .. } => {
                    bail!("WASM backend does not support field assignment. Use `ooda run`.");
                }
                Statement::Assign { name, value, .. } => {
                    if !locals.contains_key(name) {
                        // Allow assign to params (also addressable as locals in WASM)
                    }
                    let e_wat = Self::emit_expr(value, &locals)?;
                    f_wat.push_str(&e_wat);
                    f_wat.push_str(&format!("    local.set ${}\n", name));
                }
                Statement::Return(Some(expr), _) => {
                    let e_wat = Self::emit_expr(expr, &locals)?;
                    f_wat.push_str(&e_wat);
                    if is_main {
                        f_wat.push_str("    i32.wrap_i64\n");
                    }
                    f_wat.push_str("    return\n");
                    emitted_return = true;
                }
                Statement::Break(_) | Statement::Continue(_) => {
                    bail!(
                        "WASM backend does not support break/continue. Use `ooda run` or `ooda build --target c`."
                    );
                }
                Statement::Return(None, _) => {
                    if is_main {
                        f_wat.push_str("    i32.const 0\n");
                        f_wat.push_str("    return\n");
                    } else {
                        f_wat.push_str("    return\n");
                    }
                    emitted_return = true;
                }
                Statement::Expr(expr, _) => {
                    let e_wat = Self::emit_expr(expr, &locals)?;
                    f_wat.push_str(&e_wat);
                    // Statement context: drop leftover stack value for non-void calls like println.
                    if matches!(expr, Expression::Call { name, .. } if name == "println") {
                        // println is imported as (param i64) with no result — nothing to drop.
                    } else if matches!(expr, Expression::Call { .. } | Expression::Binary { .. } | Expression::Variable(_, _) | Expression::Literal(_, _)) {
                        // User fns return i64 — drop if used as statement.
                        if let Expression::Call { name, .. } = expr {
                            if name != "println" {
                                f_wat.push_str("    drop\n");
                            }
                        }
                    }
                }
                Statement::While { cond, body, .. } => {
                    f_wat.push_str(&Self::emit_while(cond, body, &locals)?);
                }
            }
        }

        // Tail expression (if any)
        if let Some(body_expr) = &func.body.expr {
            let e_wat = Self::emit_expr(body_expr, &locals)?;
            f_wat.push_str(&e_wat);
            if is_main {
                f_wat.push_str("    i32.wrap_i64\n");
            }
            f_wat.push_str("    return\n");
            emitted_return = true;
        }

        if !emitted_return {
            if is_main {
                f_wat.push_str("    i32.const 0\n    return\n");
            } else {
                f_wat.push_str("    return\n");
            }
        }

        f_wat.push_str("  )\n");
        Ok(f_wat)
    }

    /// Emit WAT for an expression.
    ///
    /// Returns the WAT fragment that leaves the expression's value on
    /// the wasm stack. The caller does NOT need to know the result
    /// type — the existing WASM ops are polymorphic over i64 / f64
    /// in the relevant slots (e.g. `local.set` accepts both). Where
    /// the type DOES matter (Binary ops, Call to typed params), the
    /// fragment internally handles promotion via `f64.convert_i64_s`.
    fn emit_expr(expr: &Expression, locals: &BTreeMap<String, &'static str>) -> Result<String> {
        let mut wat = String::new();
        match expr {
            Expression::Literal(Literal::Int(n), _) => {
                wat.push_str(&format!("    i64.const {}\n", n));
            }
            Expression::Literal(Literal::Bool(b), _) => {
                wat.push_str(&format!("    i64.const {}\n", if *b { 1 } else { 0 }));
            }
            Expression::Literal(Literal::String(_), _) => {
                bail!("WASM backend does not support string literals; use `ooda run`.");
            }
            Expression::Literal(Literal::Float(f), _) => {
                wat.push_str(&format!("    f64.const {}\n", f));
            }
            Expression::Literal(Literal::Void, _) => {
                wat.push_str("    i64.const 0\n");
            }
            Expression::Variable(name, _) => {
                // local.get is type-polymorphic — works for both i64 and f64.
                wat.push_str(&format!("    local.get ${}\n", name));
            }
            Expression::Binary { op, left, right, .. } => {
                // Infer operand types. Prefer the declared type of a
                // local; fall back to the literal shape for fresh
                // expressions.
                let lhs_ty = Self::infer_expr_type(left, locals);
                let rhs_ty = Self::infer_expr_type(right, locals);
                // Promote i64 → f64 if either operand is f64.
                let promote = |ty: &'static str, code: &mut String| {
                    if ty == "i64" && (lhs_ty == "f64" || rhs_ty == "f64") {
                        code.push_str("    f64.convert_i64_s\n");
                    }
                };
                let l_wat = Self::emit_expr(left, locals)?;
                let mut l_code = String::new();
                promote(lhs_ty, &mut l_code);
                wat.push_str(&l_wat);
                wat.push_str(&l_code);

                let r_wat = Self::emit_expr(right, locals)?;
                let mut r_code = String::new();
                promote(rhs_ty, &mut r_code);
                wat.push_str(&r_wat);
                wat.push_str(&r_code);

                // Both operands are now on the stack as the same type.
                let ty = if lhs_ty == "f64" || rhs_ty == "f64" { "f64" } else { "i64" };
                match op {
                    BinOp::Add => wat.push_str(&format!("    {}.add\n", ty)),
                    BinOp::Sub => wat.push_str(&format!("    {}.sub\n", ty)),
                    BinOp::Mul => wat.push_str(&format!("    {}.mul\n", ty)),
                    BinOp::Div if ty == "i64" => wat.push_str("    i64.div_s\n"),
                    BinOp::Div => wat.push_str("    f64.div\n"),
                    // Comparisons yield i32 in WebAssembly; extend to i64 Bool model.
                    BinOp::Eq => {
                        wat.push_str(&format!("    {}.eq\n", ty));
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    BinOp::Neq => {
                        wat.push_str(&format!("    {}.ne\n", ty));
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    BinOp::Gt => {
                        if ty == "i64" { wat.push_str("    i64.gt_s\n") } else { wat.push_str("    f64.gt\n") }
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    BinOp::Lt => {
                        if ty == "i64" { wat.push_str("    i64.lt_s\n") } else { wat.push_str("    f64.lt\n") }
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    BinOp::Gte => {
                        if ty == "i64" { wat.push_str("    i64.ge_s\n") } else { wat.push_str("    f64.ge\n") }
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    BinOp::Lte => {
                        if ty == "i64" { wat.push_str("    i64.le_s\n") } else { wat.push_str("    f64.le\n") }
                        wat.push_str("    i64.extend_i32_u\n");
                    }
                    // Boolean ops stay i64.
                    BinOp::And | BinOp::Or if ty == "i64" => match op {
                        BinOp::And => wat.push_str("    i64.and\n"),
                        BinOp::Or => wat.push_str("    i64.or\n"),
                        _ => unreachable!(),
                    },
                    BinOp::And | BinOp::Or => bail!(
                        "WASM backend does not yet lower {} on Float operands in this alpha.",
                        match op { BinOp::And => "&&", BinOp::Or => "||", _ => "?" }
                    ),
                    BinOp::DotDot | BinOp::DotDotEq => {
                        bail!("WASM backend does not yet lower range operators (`..`, `..=`). Use `ooda run`.")
                    }
                }
            }
            Expression::Call { name, args, .. } => {
                if name.starts_with('.') {
                    bail!(
                        "WASM backend does not yet support method-style calls (`{}`). Use `ooda run`.",
                        name
                    );
                }
                if name == "println" {
                    if args.is_empty() {
                        bail!("WASM println requires at least one Int argument");
                    }
                    for arg in args {
                        if matches!(arg, Expression::Literal(Literal::String(_), _)) {
                            bail!(
                                "WASM backend cannot lower println(String); use println(Int) or `ooda run`."
                            );
                        }
                        // The imported host println takes i64 — convert f64.
                        let arg_ty = Self::infer_expr_type(arg, locals);
                        wat.push_str(&Self::emit_expr(arg, locals)?);
                        if arg_ty == "f64" {
                            wat.push_str("    i64.trunc_f64_s\n");
                        }
                        wat.push_str("    call $println\n");
                    }
                } else {
                    for arg in args {
                        wat.push_str(&Self::emit_expr(arg, locals)?);
                    }
                    wat.push_str(&format!("    call ${}\n", name));
                }
            }
            Expression::If {
                cond,
                then_branch,
                else_branch,
                ..
            } => {
                wat.push_str(&Self::emit_if(cond, then_branch, else_branch.as_ref(), locals)?);
            }
            Expression::Unary { op, expr, .. } => {
                let inner_ty = Self::infer_expr_type(expr, locals);
                wat.push_str(&Self::emit_expr(expr, locals)?);
                match op {
                    UnaryOp::Not => {
                        // `!` on Int → eqz. On Float → compare ≠ 0.0 via f64.const 0.0; f64.ne.
                        match inner_ty {
                            "i64" => wat.push_str("    i64.eqz\n"),
                            "f64" => {
                                wat.push_str("    f64.const 0.0\n");
                                wat.push_str("    f64.ne\n");
                            }
                            _ => wat.push_str("    i64.eqz\n"),
                        }
                    }
                    UnaryOp::Neg => match inner_ty {
                        "i64" => {
                            wat.push_str("    i64.const -1\n");
                            wat.push_str("    i64.mul\n");
                        }
                        "f64" => {
                            wat.push_str("    f64.const -1.0\n");
                            wat.push_str("    f64.mul\n");
                        }
                        _ => {
                            wat.push_str("    i64.const -1\n");
                            wat.push_str("    i64.mul\n");
                        }
                    },
                }
            }
            Expression::While { cond, body, .. } => {
                wat.push_str(&Self::emit_while(cond, body, locals)?);
            }
            Expression::Match { .. } => {
                bail!("WASM backend does not yet lower `match` expressions; use `ooda run`.")
            }
            Expression::StructLit { .. } => {
                bail!("WASM backend does not yet lower struct literals; use `ooda run`.")
            }
        }
        Ok(wat)
    }

    /// Best-effort type inference for an expression: declared local
    /// type > literal shape > default i64.
    fn infer_expr_type(expr: &Expression, locals: &BTreeMap<String, &'static str>) -> &'static str {
        match expr {
            Expression::Literal(Literal::Float(_), _) => "f64",
            Expression::Literal(Literal::Bool(_), _) => "i64",
            Expression::Literal(Literal::Int(_), _) => "i64",
            Expression::Variable(name, _) => locals.get(name).copied().unwrap_or("i64"),
            Expression::Binary { left, right, .. } => {
                let lt = Self::infer_expr_type(left, locals);
                let rt = Self::infer_expr_type(right, locals);
                if lt == "f64" || rt == "f64" { "f64" } else { "i64" }
            }
            // Default to i64 for everything else (calls, if, etc.).
            _ => "i64",
        }
    }

    fn emit_while(
        cond: &Expression,
        body: &Block,
        locals: &BTreeMap<String, &'static str>,
    ) -> Result<String> {
        let mut wat = String::new();
        // If the condition is Float, convert to i32 (true/false).
        let cond_ty = Self::infer_expr_type(cond, locals);
        // while cond { body }  →  break when cond is *false* (zero).
        // Previous alphas inverted this (br_if on true), so loops never ran.
        wat.push_str("    block $break\n");
        wat.push_str("      loop $continue\n");
        wat.push_str(&Self::emit_expr(cond, locals)?);
        match cond_ty {
            "f64" => {
                wat.push_str("        f64.const 0.0\n");
                wat.push_str("        f64.eq\n"); // 1 when false → break
            }
            _ => {
                // i64/bool: eqz → 1 when cond==0 (false) → break
                wat.push_str("        i64.eqz\n");
            }
        }
        wat.push_str("        br_if $break\n");
        for stmt in &body.stmts {
            wat.push_str(&Self::emit_stmt_wat(stmt, locals)?);
        }
        wat.push_str("        br $continue\n");
        wat.push_str("      end\n");
        wat.push_str("    end\n");
        // The block has no result, but stack-polymorphic wasm needs
        // an inert value to satisfy validation — emit an i32.const 0.
        wat.push_str("    i32.const 0\n");
        wat.push_str("    drop\n");
        Ok(wat)
    }

/// Lower `if cond { then } else { els }` to WAT.
    ///
    /// The condition is normalised to i32 (0 = false, non-zero = true).
    /// Both branches must produce a single value of the unified
    /// type (i64 or f64) on the stack so the outer block has a
    /// uniform `(result T)` signature.
    fn emit_if(
        cond: &Expression,
        then_branch: &Block,
        else_branch: Option<&Block>,
        locals: &BTreeMap<String, &'static str>,
    ) -> Result<String> {
        // Reject `match` (not yet lowered) anywhere in the branches.
        for stmt in &then_branch.stmts {
            if matches!(stmt, Statement::Expr(expr, _) | Statement::Return(Some(expr), _)
                if matches!(expr, Expression::Match { .. }))
            {
                bail!("WASM backend does not yet lower `match` expressions; use `ooda run`.");
            }
        }
        if let Some(eb) = else_branch {
            for stmt in &eb.stmts {
                if matches!(stmt, Statement::Expr(expr, _) | Statement::Return(Some(expr), _)
                    if matches!(expr, Expression::Match { .. }))
                {
                    bail!("WASM backend does not yet lower `match` expressions; use `ooda run`.");
                }
            }
        }

        // Determine the unified result type of the if from the
        // tail expression of each branch (or default to i64).
        let branch_ty = |b: &Block| -> &'static str {
            if let Some(tail) = &b.expr {
                Self::expr_literal_type(tail, locals)
            } else {
                // Walk statements; pick the last Return's type, else Void.
                let mut ty = "i64";
                for s in &b.stmts {
                    if let Statement::Return(Some(e), _) = s {
                        ty = Self::expr_literal_type(e, locals);
                    }
                }
                ty
            }
        };
        let result_ty = if let Some(eb) = else_branch {
            let t_ty = branch_ty(then_branch);
            let e_ty = branch_ty(eb);
            if t_ty == "f64" || e_ty == "f64" { "f64" } else { "i64" }
        } else {
            branch_ty(then_branch)
        };

        let mut wat = String::new();

        // 1. Condition, normalised to i32
        wat.push_str(&Self::emit_expr(cond, locals)?);
        wat.push_str(&format!(
            "    {}.const 0\n    {}.ne\n",
            if Self::infer_expr_type(cond, locals) == "f64" { "f64" } else { "i64" },
            if Self::infer_expr_type(cond, locals) == "f64" { "f64" } else { "i64" },
        ));

        // 2. Structured if/then/else with the unified result type
        wat.push_str(&format!("    (if (result {})\n", result_ty));
        wat.push_str("      (then\n");
        for stmt in &then_branch.stmts {
            wat.push_str(&Self::emit_stmt_wat(stmt, locals)?);
        }
        wat.push_str("      )\n");
        wat.push_str("      (else\n");
        if let Some(eb) = else_branch {
            for stmt in &eb.stmts {
                wat.push_str(&Self::emit_stmt_wat(stmt, locals)?);
            }
        } else {
            // No-else branch: emit a default value of the unified type.
            wat.push_str(&format!("        {}.const 0\n", result_ty));
        }
        wat.push_str("      )\n");
        wat.push_str("    )\n");

        Ok(wat)
    }

    /// Type of a literal-shaped expression (ignores locals/operations).
    fn expr_literal_type(expr: &Expression, locals: &BTreeMap<String, &'static str>) -> &'static str {
        Self::infer_expr_type(expr, locals)
    }

    /// Emit WAT for one statement (used by `emit_if` for each
    /// branch). Mirrors the body-emission logic in `emit_function`.
    fn emit_stmt_wat(stmt: &Statement, locals: &BTreeMap<String, &'static str>) -> Result<String> {
        let mut wat = String::new();
        match stmt {
            Statement::Let { name, init, .. } => {
                wat.push_str(&Self::emit_expr(init, locals)?);
                wat.push_str(&format!("        local.set ${}\n", name));
            }
                Statement::FieldAssign { .. } => {
                    bail!("WASM backend does not support field assignment. Use `ooda run`.");
                }
            Statement::Assign { name, value, .. } => {
                wat.push_str(&Self::emit_expr(value, locals)?);
                wat.push_str(&format!("        local.set ${}\n", name));
            }
            Statement::Return(Some(expr), _) => {
                wat.push_str(&Self::emit_expr(expr, locals)?);
                wat.push_str("        return\n");
            }
            Statement::Break(_) | Statement::Continue(_) => {
                bail!("WASM backend does not support break/continue. Use `ooda run` or `ooda build --target c`.");
            }
            Statement::Return(None, _) => {
                wat.push_str("        return\n");
            }
            Statement::Expr(expr, _) => {
                wat.push_str(&Self::emit_expr(expr, locals)?);
                // Statement-context: drop non-println call results.
                if let Expression::Call { name, .. } = expr {
                    if name != "println" {
                        wat.push_str("        drop\n");
                    }
                }
            }
            Statement::While { cond, body, .. } => {
                wat.push_str(&Self::emit_while(cond, body, locals)?);
                // emit_while leaves an i32.const 0 — drop it in statement context.
                wat.push_str("        drop\n");
            }
        }
        Ok(wat)
    }

    /// Structural validation: scan the emitted WAT for undeclared locals and
    /// missing `return` instructions. Optionally round-trip with
    /// `wasm-tools validate` when available.
    fn validate_wat(wat: &str) -> Result<()> {
        if wat.is_empty() {
            bail!("WASM validation failed: empty WAT output");
        }
        // Track per-function locals.
        let mut current_locals: HashSet<String> = HashSet::new();
        let mut current_params: HashSet<String> = HashSet::new();
        let mut in_function = false;
        let mut saw_return = false;

        for line in wat.lines() {
            let t = line.trim();
            if t.starts_with("(func $") {
                if in_function && !saw_return {
                    bail!("WASM validation failed: previous function missing `return`");
                }
                in_function = true;
                saw_return = false;
                current_locals.clear();
                current_params.clear();
                // Parse `(func $name (param $p1 i64) ...`
                let after_func = t.trim_start_matches("(func $");
                if let Some(space_idx) = after_func.find(' ') {
                    let mut rest = &after_func[space_idx..];
                    // Consume export if present
                    if rest.trim_start().starts_with("(export") {
                        if let Some(close) = rest.find(')') {
                            rest = &rest[close + 1..];
                        }
                    }
                    while let Some(open) = rest.find("(param $") {
                        let after_param = &rest[open + "(param $".len()..];
                        if let Some(space_idx) = after_param.find(' ') {
                            let pname = &after_param[..space_idx];
                            current_params.insert(pname.to_string());
                            rest = &after_param[space_idx..];
                        } else {
                            break;
                        }
                    }
                }
            } else if t.starts_with("(local $") {
                let after_local = t.trim_start_matches("(local $");
                if let Some(space_idx) = after_local.find(' ') {
                    let lname = &after_local[..space_idx];
                    current_locals.insert(lname.to_string());
                }
            } else if t.starts_with("local.get $") || t.starts_with("local.set $") {
                let op = if t.starts_with("local.get") { "local.get" } else { "local.set" };
                let rest = &t[op.len() + 2..]; // skip "$" + name
                let name = rest.split_whitespace().next().unwrap_or("");
                if !current_params.contains(name) && !current_locals.contains(name) {
                    bail!(
                        "WASM validation failed: {} references undeclared local/param `${}` (must be in (param ...) or (local ...))",
                        op,
                        name
                    );
                }
            } else if t == "return" {
                saw_return = true;
            }
        }
        if in_function && !saw_return {
            bail!("WASM validation failed: last function missing `return`");
        }

        // Optional external validation
        if let Ok(status) = Self::run_wasm_tools_validate(wat) {
            if !status {
                bail!("WASM validation failed: `wasm-tools validate` rejected the WAT");
            }
        }
        Ok(())
    }

    fn run_wasm_tools_validate(wat: &str) -> Result<bool> {
        let candidates = ["wasm-tools", "wasm-tools-1", "wasm-tools-2"];
        let bin = candidates
            .into_iter()
            .find(|c| Command::new(c).arg("--version").output().is_ok());
        let Some(bin) = bin else {
            return Err(anyhow!("wasm-tools not installed"));
        };

        let dir = std::env::temp_dir().join(format!("ooda-wasm-{}", std::process::id()));
        std::fs::create_dir_all(&dir)?;
        let wat_path = dir.join("check.wat");
        std::fs::write(&wat_path, wat)?;
        let out = Command::new(bin)
            .arg("validate")
            .arg(&wat_path)
            .output()?;
        let _ = std::fs::remove_dir_all(&dir);
        Ok(out.status.success())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn parse(src: &str) -> Program {
        let mut l = Lexer::new(src);
        let tokens = l.tokenize().expect("lex");
        let mut p = Parser::new(tokens);
        p.parse_program().expect("parse")
    }

    #[test]
    fn emits_valid_wat_for_straight_line_int() {
        let prog = parse(
            r#"
            pub fn add(a: Int, b: Int) -> Int { return a + b; }
            pub fn main() { let x = add(2, 3); }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        assert!(wat.contains("(local $x i64)"), "wat:\n{}", wat);
        assert!(wat.contains("local.set $x"), "wat:\n{}", wat);
        assert!(wat.contains("i64.const 2"), "wat:\n{}", wat);
        assert!(wat.contains("i64.const 3"), "wat:\n{}", wat);
        assert!(wat.contains("call $add"), "wat:\n{}", wat);
    }

    #[test]
    fn rejects_string_literals_non_zero() {
        let prog = parse(r#"pub fn main() { let s = "hi"; }"#);
        let res = WasmCodeGen::emit_wat(&prog);
        assert!(res.is_err());
        assert!(format!("{}", res.unwrap_err()).contains("string literal"));
    }

    #[test]
    fn lowers_if_then_else_to_valid_wat() {
        let prog = parse(
            r#"
            pub fn pick(x: Int) -> Int {
                if x > 0 { return x; } else { return 0 - x; }
            }
            pub fn main() {}
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        // Both branches must produce i64 and the if must be a
        // structured (if (result i64) (then …) (else …)) block.
        assert!(wat.contains("(if (result i64)"), "wat:\n{}", wat);
        assert!(wat.contains("(then"), "wat:\n{}", wat);
        assert!(wat.contains("(else"), "wat:\n{}", wat);
    }

    #[test]
    fn lowers_if_without_else_with_default_zero_branch() {
        let prog = parse(
            r#"
            pub fn sign(x: Int) -> Int {
                if x >= 0 { return x; }
                return 0 - x;
            }
            pub fn main() {}
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        assert!(wat.contains("(if (result i64)"), "wat:\n{}", wat);
        assert!(wat.contains("i64.const 0"), "wat:\n{}", wat);
    }

    #[test]
    fn rejects_match_expressions_non_zero() {
        let prog = parse(
            r#"
            pub fn classify(x: Int) -> Int {
                match x {
                    0 => 0,
                    _ => 1,
                }
            }
            pub fn main() {}
            "#,
        );
        let res = WasmCodeGen::emit_wat(&prog);
        assert!(res.is_err());
        assert!(format!("{}", res.unwrap_err()).contains("match"));
    }

    #[test]
    fn rejects_capability_parameters_non_zero() {
        let prog = parse(
            r#"
            pub fn fetch(net: &NetCap, url: String) -> String { return fetch(url); }
            pub fn main() {}
            "#,
        );
        let res = WasmCodeGen::emit_wat(&prog);
        assert!(res.is_err());
        assert!(format!("{}", res.unwrap_err()).contains("capability"));
    }

    #[test]
    fn emits_local_decl_for_let() {
        let prog = parse(
            r#"
            pub fn main() {
                let a = 1;
                let b = 2;
                let c = a + b;
            }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        assert!(wat.contains("(local $a i64)"));
        assert!(wat.contains("(local $b i64)"));
        assert!(wat.contains("(local $c i64)"));
    }

    #[test]
    fn emits_println_int() {
        let prog = parse(
            r#"
            pub fn main() {
                let x = 42;
                println(x);
            }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        assert!(wat.contains("call $println"), "wat:\n{}", wat);
        assert!(wat.contains("local.get $x"), "wat:\n{}", wat);
    }

    #[test]
    fn emits_wasm_for_float_arithmetic() {
        let prog = parse(
            r#"
            pub fn main() {
                let x = 1.5 + 2.5;
                let y = x * 2.0;
                println(y);
            }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit");
        // Float locals are f64
        assert!(wat.contains("(local $x f64)"), "wat:\n{}", wat);
        assert!(wat.contains("(local $y f64)"), "wat:\n{}", wat);
        // Float constants and ops
        assert!(wat.contains("f64.const 1.5"), "wat:\n{}", wat);
        assert!(wat.contains("f64.const 2.5"), "wat:\n{}", wat);
        assert!(wat.contains("f64.add"), "wat:\n{}", wat);
        assert!(wat.contains("f64.mul"), "wat:\n{}", wat);
        // println is the i64 host import, so the Float value is truncated
        assert!(wat.contains("i64.trunc_f64_s"), "wat:\n{}", wat);
    }

    #[test]
    fn while_breaks_when_condition_is_false_not_true() {
        // Polarity: br_if $break must fire when cond is *false* (i64.eqz),
        // not when true (old bug inverted loops so bodies never ran).
        let prog = parse(
            r#"
            pub fn main() {
                let mut i = 0;
                while i < 3 {
                    i = i + 1;
                }
                println(i);
            }
            "#,
        );
        let wat = WasmCodeGen::emit_wat(&prog).expect("emit while");
        assert!(
            wat.contains("i64.eqz"),
            "while must break on false via i64.eqz:\n{}",
            wat
        );
        // Must not use the inverted "ne 0 → break on true" pattern.
        assert!(
            !wat.contains("i64.const 0\n        i64.ne\n        br_if $break"),
            "inverted while polarity must not appear:\n{}",
            wat
        );
        assert!(wat.contains("br_if $break"), "wat:\n{}", wat);
        assert!(wat.contains("br $continue"), "wat:\n{}", wat);
        // Comparisons produce i32 in WASM; we extend to i64 Bool model.
        assert!(
            wat.contains("i64.extend_i32_u"),
            "compare result must extend i32→i64:\n{}",
            wat
        );
    }

    #[test]
    fn rejects_match_expressions_in_wasm() {
        let prog = parse(
            r#"
            pub fn classify(x: Int) -> Int {
                match x {
                    0 => 0,
                    _ => 1,
                }
            }
            pub fn main() {}
            "#,
        );
        let res = WasmCodeGen::emit_wat(&prog);
        assert!(res.is_err());
        assert!(format!("{}", res.unwrap_err()).contains("match"));
    }
}
